
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('TO','Torino','1','758321');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VC','Vercelli','1','758322');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('NO','Novara','1','758323');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CN','Cuneo','1','758324');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AT','Asti','1','758325');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AL','Alessandria','1','758326');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BI','Biella','1','758327');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VB','Verbano-Cusio-Ossola','1','758328');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AO','Valle d''Aosta/Vallée d''Aoste','2','758329');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VA','Varese','3','758330');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CO','Como','3','758331');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('SO','Sondrio','3','758332');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('MI','Milano','3','758333');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BG','Bergamo','3','758334');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BS','Brescia','3','758335');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PV','Pavia','3','758336');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CR','Cremona','3','758337');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('MN','Mantova','3','758338');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('LC','Lecco','3','758339');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('LO','Lodi','3','758340');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('MB','Monza e della Brianza','3','758341');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BZ','Bolzano/Bozen','4','758342');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('TN','Trento','4','758343');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VR','Verona','5','758344');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VI','Vicenza','5','758345');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BL','Belluno','5','758346');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('TV','Treviso','5','758347');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VE','Venezia','5','758348');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PD','Padova','5','758349');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('RO','Rovigo','5','758350');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('UD','Udine','6','758351');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('GO','Gorizia','6','758352');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('TS','Trieste','6','758353');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PN','Pordenone','6','758354');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('IM','Imperia','7','758355');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('SV','Savona','7','758356');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('GE','Genova','7','758357');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('SP','La Spezia','7','758358');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PC','Piacenza','8','758359');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PR','Parma','8','758360');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('RE','Reggio nell''Emilia','8','758361');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('MO','Modena','8','758362');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BO','Bologna','8','758363');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('FE','Ferrara','8','758364');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('RA','Ravenna','8','758365');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('FC','Forlì-Cesena','8','758366');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('RN','Rimini','8','758367');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('MS','Massa-Carrara','9','758368');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('LU','Lucca','9','758369');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PT','Pistoia','9','758370');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('FI','Firenze','9','758371');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('LI','Livorno','9','758372');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PI','Pisa','9','758373');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AR','Arezzo','9','758374');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('SI','Siena','9','758375');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('GR','Grosseto','9','758376');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PO','Prato','9','758377');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PG','Perugia','10','758378');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('TR','Terni','10','758379');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PU','Pesaro e Urbino','11','758380');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AN','Ancona','11','758381');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('MC','Macerata','11','758382');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AP','Ascoli Piceno','11','758383');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('FM','Fermo','11','758384');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VT','Viterbo','12','758385');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('RI','Rieti','12','758386');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('RM','Roma','12','758387');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('LT','Latina','12','758388');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('FR','Frosinone','12','758389');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AQ','L''Aquila','13','758390');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('TE','Teramo','13','758391');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PE','Pescara','13','758392');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CH','Chieti','13','758393');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CB','Campobasso','14','758394');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('IS','Isernia','14','758395');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CE','Caserta','15','758396');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BN','Benevento','15','758397');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('NA','Napoli','15','758398');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AV','Avellino','15','758399');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('SA','Salerno','15','758400');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('FG','Foggia','16','758401');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BA','Bari','16','758402');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('TA','Taranto','16','758403');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BR','Brindisi','16','758404');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('LE','Lecce','16','758405');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('BT','Barletta-Andria-Trani','16','758406');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PZ','Potenza','17','758407');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('MT','Matera','17','758408');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CS','Cosenza','18','758409');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CZ','Catanzaro','18','758410');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('RC','Reggio di Calabria','18','758411');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('KR','Crotone','18','758412');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VV','Vibo Valentia','18','758413');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('TP','Trapani','19','758414');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('PA','Palermo','19','758415');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('ME','Messina','19','758416');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('AG','Agrigento','19','758417');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CL','Caltanissetta','19','758418');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('EN','Enna','19','758419');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CT','Catania','19','758420');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('RG','Ragusa','19','758421');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('SR','Siracusa','19','758422');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('SS','Sassari','20','758423');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('NU','Nuoro','20','758424');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CA','Cagliari','20','758425');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('OR','Oristano','20','758426');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('OT','Olbia-Tempio','20','758427');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('OG','Ogliastra','20','758428');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('VS','Medio Campidano','20','758429');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('CI','Carbonia-Iglesias','20','758430');
INSERT INTO shared.districts(mnemonic,description,region,district) VALUES ('EE','Provincia ***ERRATA***','1','758431');
