format
INSERT INTO public.regions(region,description,geographical_area) VALUES ('1000000000','Piemonte_test','North-west');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('2000000000','Valle d''Aosta/Vallée d''Aoste_test','North-west');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('3000000000','Lombardia_test','North-west');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('4000000000','Trentino-Alto Adige/Südtirol_test','North-east');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('5000000000','Veneto_test','North-east');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('6000000000','Friuli-Venezia Giulia_test','North-east');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('7000000000','Liguria_test','North-west');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('8000000000','Emilia-Romagna_test','North-east');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('9000000000','Toscana_test','Center');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('10000000000','Umbria_test','Center');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('11000000000','Marche_test','Center');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('12000000000','Lazio_test','Center');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('13000000000','Abruzzo_test','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('14000000000','Molise_test','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('15000000000','Campania_test','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('16000000000','Puglia_test','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('17000000000','Basilicata_test','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('18000000000','Calabria_test','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('19000000000','Sicilia_test','Islands');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('20000000000','Sardegna_test','Islands');
