format
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('1','Piemonte','North-west');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('2','Valle d''Aosta/Vallée d''Aoste','North-west');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('3','Lombardia','North-west');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('4','Trentino-Alto Adige/Südtirol','North-east');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('5','Veneto','North-east');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('6','Friuli-Venezia Giulia','North-east');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('7','Liguria','North-west');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('8','Emilia-Romagna','North-east');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('9','Toscana','Center');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('10','Umbria','Center');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('11','Marche','Center');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('12','Lazio','Center');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('13','Abruzzo','South');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('14','Molise','South');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('15','Campania','South');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('16','Puglia','South');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('17','Basilicata','South');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('18','Calabria','South');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('19','Sicilia','Islands');
INSERT INTO shared.regions(region,description,geographical_area) VALUES ('20','Sardegna','Islands');
