-- ATTENZIONE personalizzare il comando cambiando: fol@fulcro.net con la propria email;
/*;
CREATE ROLE "fol@fulcro.net" LOGIN ENCRYPTED PASSWORD '*password*' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT scuola247_supervisor TO " *email* " WITH ADMIN OPTION;
*/;
/* GRANT SINGOLI */;
REVOKE scuola247_employee FROM scuola247_user;
REVOKE scuola247_executive FROM scuola247_user;
REVOKE scuola247_relative FROM scuola247_user;
REVOKE scuola247_student FROM scuola247_user;
REVOKE scuola247_teacher FROM scuola247_user;
REVOKE scuola247_supervisor FROM scuola247_user;

REVOKE scuola247_user FROM scuola247_employee;
REVOKE scuola247_executive FROM scuola247_employee;
REVOKE scuola247_relative FROM scuola247_employee;
REVOKE scuola247_student FROM scuola247_employee;
REVOKE scuola247_teacher FROM scuola247_employee;
REVOKE scuola247_supervisor FROM scuola247_employee;

REVOKE scuola247_user FROM scuola247_executive;
REVOKE scuola247_employee FROM scuola247_executive;
REVOKE scuola247_relative FROM scuola247_executive;
REVOKE scuola247_student FROM scuola247_executive;
REVOKE scuola247_teacher FROM scuola247_executive;
REVOKE scuola247_supervisor FROM scuola247_executive;

REVOKE scuola247_user FROM scuola247_relative;
REVOKE scuola247_employee FROM scuola247_relative;
REVOKE scuola247_executive FROM scuola247_relative;
REVOKE scuola247_student FROM scuola247_relative;
REVOKE scuola247_teacher FROM scuola247_relative;
REVOKE scuola247_supervisor FROM scuola247_relative;

REVOKE scuola247_user FROM scuola247_student;
REVOKE scuola247_employee FROM scuola247_student;
REVOKE scuola247_executive FROM scuola247_student;
REVOKE scuola247_relative FROM scuola247_student;
REVOKE scuola247_teacher FROM scuola247_student;
REVOKE scuola247_supervisor FROM scuola247_student;

REVOKE scuola247_user FROM scuola247_teacher;
REVOKE scuola247_employee FROM scuola247_teacher;
REVOKE scuola247_executive FROM scuola247_teacher;
REVOKE scuola247_relative FROM scuola247_teacher;
REVOKE scuola247_student FROM scuola247_teacher;
REVOKE scuola247_supervisor FROM scuola247_teacher;

REVOKE scuola247_user FROM scuola247_supervisor;
REVOKE scuola247_employee FROM scuola247_supervisor;
REVOKE scuola247_executive FROM scuola247_supervisor;
REVOKE scuola247_relative FROM scuola247_supervisor;
REVOKE scuola247_student FROM scuola247_supervisor;
REVOKE scuola247_teacher FROM scuola247_supervisor;
REVOKE scuola247_supervisor FROM scuola247_supervisor;

GRANT scuola247_user TO scuola247_employee;
GRANT scuola247_user TO scuola247_executive;
GRANT scuola247_user TO scuola247_teacher;
GRANT scuola247_user TO scuola247_relative;
GRANT scuola247_user TO scuola247_student;
GRANT scuola247_employee TO scuola247_supervisor;
GRANT scuola247_executive TO scuola247_supervisor;
GRANT scuola247_relative TO scuola247_supervisor;
GRANT scuola247_student TO scuola247_supervisor;
GRANT scuola247_teacher TO scuola247_supervisor;
GRANT scuola247_user TO scuola247_supervisor;

REVOKE ALL ON DATABASE scuola247 FROM public;
REVOKE ALL ON DATABASE scuola247 FROM scuola247_supervisor;
REVOKE ALL ON DATABASE scuola247 FROM scuola247_executive;
REVOKE ALL ON DATABASE scuola247 FROM scuola247_employee;
REVOKE ALL ON DATABASE scuola247 FROM scuola247_teacher;
REVOKE ALL ON DATABASE scuola247 FROM scuola247_relative;
REVOKE ALL ON DATABASE scuola247 FROM scuola247_student;
REVOKE ALL ON DATABASE scuola247 FROM scuola247_user;

GRANT ALL ON DATABASE scuola247 TO scuola247_supervisor WITH GRANT OPTION;
GRANT CONNECT ON DATABASE scuola247 TO scuola247_user;

GRANT ALL ON LANGUAGE plpgsql TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON LANGUAGE plpgsql TO scuola247_user;

/* GRANT SU TUTTI I SCHEMA */;
-- ASSERT;
REVOKE ALL ON SCHEMA assert FROM public;
REVOKE ALL ON SCHEMA assert FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA assert FROM scuola247_executive;
REVOKE ALL ON SCHEMA assert FROM scuola247_employee;
REVOKE ALL ON SCHEMA assert FROM scuola247_teacher;
REVOKE ALL ON SCHEMA assert FROM scuola247_relative;
REVOKE ALL ON SCHEMA assert FROM scuola247_student;
REVOKE ALL ON SCHEMA assert FROM scuola247_user;

GRANT ALL ON SCHEMA assert TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA assert TO scuola247_user;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA assert TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA assert TO scuola247_user;

-- DATASETS;
REVOKE ALL ON SCHEMA datasets FROM public;
REVOKE ALL ON SCHEMA datasets FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA datasets FROM scuola247_executive;
REVOKE ALL ON SCHEMA datasets FROM scuola247_employee;
REVOKE ALL ON SCHEMA datasets FROM scuola247_teacher;
REVOKE ALL ON SCHEMA datasets FROM scuola247_relative;
REVOKE ALL ON SCHEMA datasets FROM scuola247_student;
REVOKE ALL ON SCHEMA datasets FROM scuola247_user;

GRANT ALL ON SCHEMA datasets TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA datasets TO scuola247_user;

GRANT ALL ON ALL TABLES IN SCHEMA datasets TO scuola247_supervisor WITH GRANT OPTION;
GRANT SELECT ON ALL TABLES IN SCHEMA datasets TO scuola247_user;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA datasets TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA datasets TO scuola247_user;

GRANT ALL ON ALL SEQUENCES IN SCHEMA datasets TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA datasets TO scuola247_user;

-- DIAGNOSTIC;
REVOKE ALL ON SCHEMA diagnostic FROM public;
REVOKE ALL ON SCHEMA diagnostic FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA diagnostic FROM scuola247_executive;
REVOKE ALL ON SCHEMA diagnostic FROM scuola247_employee;
REVOKE ALL ON SCHEMA diagnostic FROM scuola247_teacher;
REVOKE ALL ON SCHEMA diagnostic FROM scuola247_relative;
REVOKE ALL ON SCHEMA diagnostic FROM scuola247_student;
REVOKE ALL ON SCHEMA diagnostic FROM scuola247_user;

GRANT ALL ON SCHEMA diagnostic TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA diagnostic TO scuola247_user;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA diagnostic TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA diagnostic TO scuola247_user;

GRANT ALL ON TYPE diagnostic.error TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON TYPE diagnostic.error TO scuola247_user;

GRANT ALL ON TYPE diagnostic.verbosities TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON TYPE diagnostic.verbosities TO scuola247_user;

-- GIT;
REVOKE ALL ON SCHEMA git FROM public;
REVOKE ALL ON SCHEMA git FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA git FROM scuola247_executive;
REVOKE ALL ON SCHEMA git FROM scuola247_employee;
REVOKE ALL ON SCHEMA git FROM scuola247_teacher;
REVOKE ALL ON SCHEMA git FROM scuola247_relative;
REVOKE ALL ON SCHEMA git FROM scuola247_student;
REVOKE ALL ON SCHEMA git FROM scuola247_user;

GRANT ALL ON SCHEMA git TO scuola247_supervisor WITH GRANT OPTION;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA git TO scuola247_supervisor WITH GRANT OPTION;

GRANT ALL ON ALL TABLES IN SCHEMA git TO scuola247_supervisor WITH GRANT OPTION;

GRANT ALL ON TYPE git.options TO scuola247_supervisor WITH GRANT OPTION;

-- PUBLIC;
REVOKE ALL ON SCHEMA public FROM public;
REVOKE ALL ON SCHEMA public FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA public FROM scuola247_executive;
REVOKE ALL ON SCHEMA public FROM scuola247_employee;
REVOKE ALL ON SCHEMA public FROM scuola247_teacher;
REVOKE ALL ON SCHEMA public FROM scuola247_relative;
REVOKE ALL ON SCHEMA public FROM scuola247_student;
REVOKE ALL ON SCHEMA public FROM scuola247_user;

GRANT ALL ON SCHEMA public TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA public TO scuola247_user;

GRANT ALL ON DOMAIN public.course_year TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON DOMAIN public.mime_type_image TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON DOMAIN public.period_lesson TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON DOMAIN public.week TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON DOMAIN public.week_day TO scuola247_supervisor WITH GRANT OPTION;

GRANT USAGE ON DOMAIN public.course_year TO scuola247_user WITH GRANT OPTION;
GRANT USAGE ON DOMAIN public.mime_type_image TO scuola247_user WITH GRANT OPTION;
GRANT USAGE ON DOMAIN public.period_lesson TO scuola247_user WITH GRANT OPTION;
GRANT USAGE ON DOMAIN public.week TO scuola247_user WITH GRANT OPTION;
GRANT USAGE ON DOMAIN public.week_day TO scuola247_user WITH GRANT OPTION;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO scuola247_user;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO scuola247_user;

GRANT ALL ON ALL TABLES IN SCHEMA public TO scuola247_supervisor WITH GRANT OPTION;

GRANT ALL ON TYPE public.address_type TO scuola247_supervisor;
GRANT ALL ON TYPE public.explanation_type TO scuola247_supervisor;
GRANT ALL ON TYPE public.file_extension TO scuola247_supervisor;
GRANT ALL ON TYPE public.gbtreekey16 TO scuola247_supervisor;
GRANT ALL ON TYPE public.gbtreekey32 TO scuola247_supervisor;
GRANT ALL ON TYPE public.gbtreekey4 TO scuola247_supervisor;
GRANT ALL ON TYPE public.gbtreekey8 TO scuola247_supervisor;
GRANT ALL ON TYPE public.gbtreekey_var TO scuola247_supervisor;
GRANT ALL ON TYPE public.geographical_area TO scuola247_supervisor;
GRANT ALL ON TYPE public.image TO scuola247_supervisor;
GRANT ALL ON TYPE public.language TO scuola247_supervisor;
GRANT ALL ON TYPE public.marital_status TO scuola247_supervisor;
GRANT ALL ON TYPE public.mime_type TO scuola247_supervisor;
GRANT ALL ON TYPE public.relationships TO scuola247_supervisor;
GRANT ALL ON TYPE public.role TO scuola247_supervisor;
GRANT ALL ON TYPE public.sex TO scuola247_supervisor;
GRANT ALL ON TYPE public.wikimedia_type TO scuola247_supervisor;

GRANT USAGE ON TYPE public.address_type TO scuola247_user;
GRANT USAGE ON TYPE public.explanation_type TO scuola247_user;
GRANT USAGE ON TYPE public.file_extension TO scuola247_user;
GRANT USAGE ON TYPE public.gbtreekey16 TO scuola247_user;
GRANT USAGE ON TYPE public.gbtreekey32 TO scuola247_user;
GRANT USAGE ON TYPE public.gbtreekey4 TO scuola247_user;
GRANT USAGE ON TYPE public.gbtreekey8 TO scuola247_user;
GRANT USAGE ON TYPE public.gbtreekey_var TO scuola247_user;
GRANT USAGE ON TYPE public.geographical_area TO scuola247_user;
GRANT USAGE ON TYPE public.image TO scuola247_user;
GRANT USAGE ON TYPE public.language TO scuola247_user;
GRANT USAGE ON TYPE public.marital_status TO scuola247_user;
GRANT USAGE ON TYPE public.mime_type TO scuola247_user;
GRANT USAGE ON TYPE public.relationships TO scuola247_user;
GRANT USAGE ON TYPE public.role TO scuola247_user;
GRANT USAGE ON TYPE public.sex TO scuola247_user;
GRANT USAGE ON TYPE public.wikimedia_type TO scuola247_user;

-- TRANSLATE;
REVOKE ALL ON SCHEMA translate FROM public;
REVOKE ALL ON SCHEMA translate FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA translate FROM scuola247_executive;
REVOKE ALL ON SCHEMA translate FROM scuola247_employee;
REVOKE ALL ON SCHEMA translate FROM scuola247_teacher;
REVOKE ALL ON SCHEMA translate FROM scuola247_relative;
REVOKE ALL ON SCHEMA translate FROM scuola247_student;
REVOKE ALL ON SCHEMA translate FROM scuola247_user;

GRANT ALL ON SCHEMA translate TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA translate TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON ALL SEQUENCES IN SCHEMA translate TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON ALL TABLES IN SCHEMA translate TO scuola247_supervisor WITH GRANT OPTION;

-- UNIT_TESTING;
REVOKE ALL ON SCHEMA unit_testing FROM public;
REVOKE ALL ON SCHEMA unit_testing FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA unit_testing FROM scuola247_executive;
REVOKE ALL ON SCHEMA unit_testing FROM scuola247_employee;
REVOKE ALL ON SCHEMA unit_testing FROM scuola247_teacher;
REVOKE ALL ON SCHEMA unit_testing FROM scuola247_relative;
REVOKE ALL ON SCHEMA unit_testing FROM scuola247_student;
REVOKE ALL ON SCHEMA unit_testing FROM scuola247_user;

GRANT ALL ON SCHEMA unit_testing TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA unit_testing TO scuola247_user;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA unit_testing TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA unit_testing TO scuola247_user;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO scuola247_user;

GRANT ALL ON ALL TABLES IN SCHEMA public TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON ALL TABLES IN SCHEMA public TO scuola247_user;

GRANT ALL ON TYPE unit_testing.check_point TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON TYPE unit_testing.check_point_status TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON TYPE unit_testing.unit_test_result TO scuola247_supervisor WITH GRANT OPTION;

GRANT ALL ON TYPE unit_testing.check_point TO scuola247_user WITH GRANT OPTION;
GRANT ALL ON TYPE unit_testing.check_point_status TO scuola247_user WITH GRANT OPTION;
GRANT ALL ON TYPE unit_testing.unit_test_result TO scuola247_user WITH GRANT OPTION;

-- UNIT_TESTS_DATASETS;
REVOKE ALL ON SCHEMA unit_tests_datasets FROM public;
REVOKE ALL ON SCHEMA unit_tests_datasets FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA unit_tests_datasets FROM scuola247_executive;
REVOKE ALL ON SCHEMA unit_tests_datasets FROM scuola247_employee;
REVOKE ALL ON SCHEMA unit_tests_datasets FROM scuola247_teacher;
REVOKE ALL ON SCHEMA unit_tests_datasets FROM scuola247_relative;
REVOKE ALL ON SCHEMA unit_tests_datasets FROM scuola247_student;
REVOKE ALL ON SCHEMA unit_tests_datasets FROM scuola247_user;

GRANT ALL ON SCHEMA unit_tests_datasets TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA unit_tests_datasets TO scuola247_user;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA unit_tests_datasets TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA unit_tests_datasets TO scuola247_user;

-- UNIT_TESTS_PUBLIC;
REVOKE ALL ON SCHEMA unit_tests_public FROM public;
REVOKE ALL ON SCHEMA unit_tests_public FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA unit_tests_public FROM scuola247_executive;
REVOKE ALL ON SCHEMA unit_tests_public FROM scuola247_employee;
REVOKE ALL ON SCHEMA unit_tests_public FROM scuola247_teacher;
REVOKE ALL ON SCHEMA unit_tests_public FROM scuola247_relative;
REVOKE ALL ON SCHEMA unit_tests_public FROM scuola247_student;
REVOKE ALL ON SCHEMA unit_tests_public FROM scuola247_user;

GRANT ALL ON SCHEMA unit_tests_public TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA unit_tests_public TO scuola247_user;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA unit_tests_public TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA unit_tests_public TO scuola247_user;

-- UNIT_TESTS_SECURITY;
REVOKE ALL ON SCHEMA unit_tests_security FROM public;
REVOKE ALL ON SCHEMA unit_tests_security FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA unit_tests_security FROM scuola247_executive;
REVOKE ALL ON SCHEMA unit_tests_security FROM scuola247_employee;
REVOKE ALL ON SCHEMA unit_tests_security FROM scuola247_teacher;
REVOKE ALL ON SCHEMA unit_tests_security FROM scuola247_relative;
REVOKE ALL ON SCHEMA unit_tests_security FROM scuola247_student;
REVOKE ALL ON SCHEMA unit_tests_security FROM scuola247_user;

GRANT ALL ON SCHEMA unit_tests_security TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA unit_tests_security TO scuola247_user;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA unit_tests_security TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA unit_tests_security TO scuola247_user;

-- UNIT_TESTS_TRANSLATE;
REVOKE ALL ON SCHEMA unit_tests_translate FROM public;
REVOKE ALL ON SCHEMA unit_tests_translate FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA unit_tests_translate FROM scuola247_executive;
REVOKE ALL ON SCHEMA unit_tests_translate FROM scuola247_employee;
REVOKE ALL ON SCHEMA unit_tests_translate FROM scuola247_teacher;
REVOKE ALL ON SCHEMA unit_tests_translate FROM scuola247_relative;
REVOKE ALL ON SCHEMA unit_tests_translate FROM scuola247_student;
REVOKE ALL ON SCHEMA unit_tests_translate FROM scuola247_user;

GRANT ALL ON SCHEMA unit_tests_translate TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA unit_tests_translate TO scuola247_user;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA unit_tests_translate TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA unit_tests_translate TO scuola247_user;

-- UTILITY;
REVOKE ALL ON SCHEMA utility FROM public;
REVOKE ALL ON SCHEMA utility FROM scuola247_supervisor;
REVOKE ALL ON SCHEMA utility FROM scuola247_executive;
REVOKE ALL ON SCHEMA utility FROM scuola247_employee;
REVOKE ALL ON SCHEMA utility FROM scuola247_teacher;
REVOKE ALL ON SCHEMA utility FROM scuola247_relative;
REVOKE ALL ON SCHEMA utility FROM scuola247_student;
REVOKE ALL ON SCHEMA utility FROM scuola247_user;

GRANT ALL ON SCHEMA utility TO scuola247_supervisor WITH GRANT OPTION;
GRANT USAGE ON SCHEMA utility TO scuola247_user;

GRANT ALL ON DOMAIN utility.number_base34 TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON DOMAIN utility.week_day TO scuola247_supervisor WITH GRANT OPTION;

GRANT USAGE ON DOMAIN utility.number_base34 TO scuola247_user WITH GRANT OPTION;
GRANT USAGE ON DOMAIN utility.week_day TO scuola247_user WITH GRANT OPTION;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA utility TO scuola247_supervisor WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA utility TO scuola247_user;

GRANT ALL ON TYPE utility.language TO scuola247_supervisor WITH GRANT OPTION;
GRANT ALL ON TYPE utility.system_message TO scuola247_supervisor WITH GRANT OPTION;

GRANT USAGE ON TYPE utility.language TO scuola247_user;
GRANT USAGE ON TYPE utility.system_message TO scuola247_user;


ALTER  OPERATOR utility.+(utility.number_base34, int4) OWNER TO scuola247_supervisor;








ALTER DOMAIN public.course_year OWNER TO scuola247_supervisor;
ALTER DOMAIN public.mime_type_image OWNER TO scuola247_supervisor;
ALTER DOMAIN public.period_lesson OWNER TO scuola247_supervisor;
ALTER DOMAIN public.week OWNER TO scuola247_supervisor;
ALTER DOMAIN public.week_day OWNER TO scuola247_supervisor;




/* DROP DELLA FUNZIONE create_role(boolean) */;
DROP FUNCTION unit_tests_security.create_role(boolean);
/* SISTEMAZIONE RUOLI */;
-- scuola247_student;
REVOKE scuola247_relative FROM "student-a@scuola-1.it";
GRANT scuola247_student TO "student-a@scuola-1.it";
REVOKE scuola247_relative FROM "student-b@scuola-1.it";
GRANT scuola247_student TO "student-b@scuola-1.it";
REVOKE scuola247_relative FROM "student-c@scuola-2.it";
GRANT scuola247_student TO "student-c@scuola-2.it";
REVOKE scuola247_relative FROM "student-d@scuola-2.it";
GRANT scuola247_student TO "student-d@scuola-2.it";
REVOKE scuola247_relative FROM "student-e@scuola-28961.it";
GRANT scuola247_student TO "student-e@scuola-28961.it";
REVOKE scuola247_relative FROM "student-f@scuola-28961.it";
GRANT scuola247_student TO "student-f@scuola-28961.it";
-- scuola247_teacher;
REVOKE scuola247_relative FROM "teacher-a@scuola-1.it";
GRANT scuola247_teacher TO "teacher-a@scuola-1.it";
REVOKE scuola247_relative FROM "teacher-b@scuola-1.it";
GRANT scuola247_teacher TO "teacher-b@scuola-1.it";
REVOKE scuola247_relative FROM "teacher-c@scuola-2.it";
GRANT scuola247_teacher TO "teacher-c@scuola-2.it";
REVOKE scuola247_relative FROM "teacher-d@scuola-2.it";
GRANT scuola247_teacher TO "teacher-d@scuola-2.it";
REVOKE scuola247_relative FROM "teacher-e@scuola-28961.it";
GRANT scuola247_teacher TO "teacher-e@scuola-28961.it";
REVOKE scuola247_relative FROM "teacher-f@scuola-28961.it";
GRANT scuola247_teacher TO "teacher-f@scuola-28961.it";
/* CREAZIONE DI RUOLI MANCANTI */;
-- scuola247_employee;
CREATE ROLE "employee-a@scuola-1.it" LOGIN ENCRYPTED PASSWORD 'password' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT scuola247_employee TO "employee-a@scuola-1.it";
CREATE ROLE "employee-b@scuola-1.it" LOGIN ENCRYPTED PASSWORD 'password' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT scuola247_employee TO "employee-b@scuola-1.it";
CREATE ROLE "employee-c@scuola-2.it" LOGIN ENCRYPTED PASSWORD 'password' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT scuola247_employee TO "employee-c@scuola-2.it";
CREATE ROLE "employee-d@scuola-2.it" LOGIN ENCRYPTED PASSWORD 'password' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT scuola247_employee TO "employee-d@scuola-2.it";
CREATE ROLE "employee-e@scuola-28961.it" LOGIN ENCRYPTED PASSWORD 'password' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT scuola247_employee TO "employee-e@scuola-28961.it";
CREATE ROLE "employee-f@scuola-28961.it" LOGIN ENCRYPTED PASSWORD 'password' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT scuola247_employee TO "employee-f@scuola-28961.it";
/* TRIGGER */;
ALTER FUNCTION public.tr_absences_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_classrooms_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_classrooms_students_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_communications_media_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_conversations_invites_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_delays_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_explanations_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_faults_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_valutations_d() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_valutations_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_valutations_qua_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_leavings_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_lessons_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_messages_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_messages_read_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_notes_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_notes_signed_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_out_of_classrooms_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_parents_meetings_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_schools_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_signatures_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_teachears_notes_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_topics_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_valutations_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_valutations_qualifications_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.tr_dependencies_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.tr_function_versions_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.tr_unit_test_sets_details_iu() OWNER TO scuola247_supervisor;
/* FUNCTIONS */;
ALTER FUNCTION unit_tests_public._after_data_insert(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.absences(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.absences_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.absences_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_security.absences_student(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_security.absences_supervisor(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.absences_triggers(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.are_equals(text, text, anyarray) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.are_not_equals(text, text, anyarray) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.branches(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.branches_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.branches_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.build_function_dependencies(text, text[]) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.build_my_sqlcode() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.cash_dist(money, money) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.cities(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.cities_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.cities_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.cities_lookup(character) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.classroom_students_ex(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.classrooms(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.classrooms_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.classrooms_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.classrooms_list(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.classrooms_lookup(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.classrooms_lookup(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.classrooms_students(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.classrooms_students_addresses_ex_by_classroom(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.classrooms_students_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.classrooms_students_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.classrooms_students_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.classrooms_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.communication_media_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.communication_types(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.communication_types_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.communication_types_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.communications_media(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.communications_media_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.communications_media_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.connectby(text, text, text, text, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.connectby(text, text, text, text, integer, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.connectby(text, text, text, text, text, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.connectby(text, text, text, text, text, integer, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.conversations(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.conversations_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.conversations_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.conversations_invites(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.count_unit_tests() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.count_unit_tests_level() OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.count_value(text, text, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.countries(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.countries_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.countries_da_buttare(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.crosstab(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.crosstab(text, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.crosstab(text, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.crosstab2(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.crosstab3(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.crosstab4(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.current_persons() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.date_dist(date, date) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.day_name(utility.week_day) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.degrees(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.degrees_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.degrees_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.delays(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.delays_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.delays_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.delays_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.districts(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.districts_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.districts_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.districts_lookup(character) OWNER TO scuola247_supervisor;
ALTER FUNCTION datasets.entity2char(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION datasets.entity_coding() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_datasets.entity_coding(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_datasets.entity_coding_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.enum2array(anyenum) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.explanations(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.explanations_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.explanations_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.explanations_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.export_table(text, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.fail(text, text, text, diagnostic.error) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.faults(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.faults_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.faults_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.faults_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.file_extension(mime_type) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.float4_dist(real, real) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.float8_dist(double precision, double precision) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.fol_test(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.full_function_name(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.function_exists(regprocedure) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.function_name(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.function_syntax_error(text, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.function_versions_synch() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bit_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bit_consistent(internal, bit, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bit_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bit_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bit_same(gbtreekey_var, gbtreekey_var, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bit_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bpchar_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bpchar_consistent(internal, character, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bytea_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bytea_consistent(internal, bytea, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bytea_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bytea_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bytea_same(gbtreekey_var, gbtreekey_var, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_bytea_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_cash_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_cash_consistent(internal, money, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_cash_distance(internal, money, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_cash_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_cash_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_cash_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_cash_same(gbtreekey16, gbtreekey16, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_cash_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_date_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_date_consistent(internal, date, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_date_distance(internal, date, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_date_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_date_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_date_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_date_same(gbtreekey8, gbtreekey8, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_date_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_decompress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_enum_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_enum_consistent(internal, anyenum, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_enum_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_enum_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_enum_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_enum_same(gbtreekey8, gbtreekey8, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_enum_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float4_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float4_consistent(internal, real, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float4_distance(internal, real, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float4_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float4_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float4_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float4_same(gbtreekey8, gbtreekey8, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float4_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float8_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float8_consistent(internal, double precision, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float8_distance(internal, double precision, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float8_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float8_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float8_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float8_same(gbtreekey16, gbtreekey16, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_float8_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_inet_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_inet_consistent(internal, inet, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_inet_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_inet_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_inet_same(gbtreekey16, gbtreekey16, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_inet_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int2_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int2_consistent(internal, smallint, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int2_distance(internal, smallint, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int2_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int2_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int2_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int2_same(gbtreekey4, gbtreekey4, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int2_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int4_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int4_consistent(internal, integer, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int4_distance(internal, integer, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int4_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int4_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int4_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int4_same(gbtreekey8, gbtreekey8, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int4_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int8_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int8_consistent(internal, bigint, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int8_distance(internal, bigint, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int8_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int8_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int8_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int8_same(gbtreekey16, gbtreekey16, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_int8_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_consistent(internal, interval, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_decompress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_distance(internal, interval, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_same(gbtreekey32, gbtreekey32, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_intv_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad8_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad8_consistent(internal, macaddr8, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad8_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad8_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad8_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad8_same(gbtreekey16, gbtreekey16, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad8_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad_consistent(internal, macaddr, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad_same(gbtreekey16, gbtreekey16, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_macad_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_numeric_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_numeric_consistent(internal, numeric, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_numeric_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_numeric_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_numeric_same(gbtreekey_var, gbtreekey_var, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_numeric_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_oid_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_oid_consistent(internal, oid, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_oid_distance(internal, oid, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_oid_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_oid_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_oid_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_oid_same(gbtreekey8, gbtreekey8, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_oid_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_text_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_text_consistent(internal, text, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_text_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_text_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_text_same(gbtreekey_var, gbtreekey_var, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_text_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_time_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_time_consistent(internal, time without time zone, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_time_distance(internal, time without time zone, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_time_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_time_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_time_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_time_same(gbtreekey16, gbtreekey16, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_time_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_timetz_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_timetz_consistent(internal, time with time zone, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_ts_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_ts_consistent(internal, timestamp without time zone, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_ts_distance(internal, timestamp without time zone, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_ts_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_ts_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_ts_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_ts_same(gbtreekey16, gbtreekey16, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_ts_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_tstz_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_tstz_consistent(internal, timestamp with time zone, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_tstz_distance(internal, timestamp with time zone, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_uuid_compress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_uuid_consistent(internal, uuid, smallint, oid, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_uuid_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_uuid_penalty(internal, internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_uuid_picksplit(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_uuid_same(gbtreekey32, gbtreekey32, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_uuid_union(internal, internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_var_decompress(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbt_var_fetch(internal) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey16_in(cstring) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey16_out(gbtreekey16) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey32_in(cstring) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey32_out(gbtreekey32) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey4_in(cstring) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey4_out(gbtreekey4) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey8_in(cstring) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey8_out(gbtreekey8) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey_var_in(cstring) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.gbtreekey_var_out(gbtreekey_var) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.get_max_column_value(text, text, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grade_types(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.grade_types_by_subject(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grade_types_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grade_types_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grades(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.grades_by_metric(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grades_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grades_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_close(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_valutations(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_valutations_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_valutations_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_valutations_qua(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_valutations_qua_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_valutations_qua_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_valutations_qua_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.grading_meetings_valutations_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.grid_valutations_columns_by_classroom_teacher_subject(bigint, bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.grid_valutations_rows_by_classroom_teacher_subject(bigint, bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.holidays(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.holidays_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.holidays_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http(http_request) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http_delete(character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http_get(character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http_head(character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http_header(character varying, character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http_post(character varying, character varying, character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http_put(character varying, character varying, character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http_reset_curlopt() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.http_set_curlopt(character varying, character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.if_function_compile(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.if_view_works(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.in_any_roles(role[]) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.in_any_roles(bigint, role[]) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.in_any_roles(character varying, role[]) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.int2_dist(smallint, smallint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.int4_dist(integer, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.int8(utility.number_base34) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.int8_dist(bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.interval_dist(interval, interval) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.is_false(text, text, boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.is_greater_than(text, text, anyelement, anyelement) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.is_less_than(text, text, anyelement, anyelement) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.is_not_null(text, text, anyelement) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.is_null(text, text, anyelement) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.is_true(text, text, boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.italian_fiscal_code(character varying, character varying, sex, date, smallint, character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.italian_fiscal_code_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.leavings(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.leavings_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.leavings_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.leavings_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.lessons(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.lessons_by_teacher_classroom_subject(bigint, bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.lessons_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.lessons_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.lessons_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.login(text, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.messages(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.messages_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.messages_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.messages_read(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.messages_read_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.messages_read_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.messages_read_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.messages_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.metrics(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.metrics_by_school(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.metrics_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.metrics_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.mime_type(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.mime_type(file_extension) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.my_sqlcode(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.my_sqlcode(character varying, character) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.normal_rand(integer, double precision, double precision) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.notes(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.notes_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.notes_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.notes_signed(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.notes_signed_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.notes_signed_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.notes_signed_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.notes_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.number_base34(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.number_base34_pl(utility.number_base34, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.oid_dist(oid, oid) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.out_of_classrooms(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.out_of_classrooms_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.out_of_classrooms_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.out_of_classrooms_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.parents_meetings(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.parents_meetings_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.parents_meetings_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.parents_meetings_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.pass(text, text, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_addresses(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_addresses_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_addresses_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.persons_lookup(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.persons_lookup(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_relations(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_relations_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_relations_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_roles(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_roles_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.persons_roles_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.persons_sel_thumbnail(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.persons_surname_name(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.photo_default() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_abort_target(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_attach_to_port(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_continue(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_create_listener() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_deposit_value(integer, text, integer, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_drop_breakpoint(integer, oid, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_get_breakpoints(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_get_proxy_info() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_get_source(integer, oid) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_get_stack(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_get_target_info(text, "char") OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_get_variables(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_oid_debug(oid) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_select_frame(integer, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_set_breakpoint(integer, oid, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_set_global_breakpoint(integer, oid, integer, integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_step_into(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_step_over(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_wait_for_breakpoint(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.pldbg_wait_for_target(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.plpgsql_check_function(regprocedure, regclass, text, boolean, boolean, boolean, boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.plpgsql_check_function_tb(regprocedure, regclass, boolean, boolean, boolean, boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.plpgsql_oid_debug(oid) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.qualifications(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.qualifications_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.qualifications_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.qualifications_plan(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.qualifications_plan_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.qualifications_plan_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.qualifications_tree() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.regions(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.regions_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.regions_lookup(smallint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.regions_lookup(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.relatives_by_classroom(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.roles_by_session_user() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.run(text, boolean, boolean, boolean, bigint, oid, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.run_ex(text, boolean, boolean, boolean, bigint, oid, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.school_years(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.school_years_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.school_years_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.school_years_list(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.school_years_lookup(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.school_years_lookup(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.schools(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.schools_behavior(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_by_description(character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.schools_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_del(bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_del_cascade(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_enabled() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.schools_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_ins(character varying, character varying, character varying, boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_ins(character varying, character varying, character varying, boolean, image) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_lookup(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_lookup(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_sel(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_sel_logo(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.schools_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_upd(bigint, bigint, character varying, character varying, character varying, boolean, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_upd(bigint, bigint, character varying, character varying, character varying, boolean, bigint, image) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.schools_upd_logo(bigint, bigint, image) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.session_person(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.session_persons() OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.set_all_sequences_2_the_max() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.set_continuous_integration(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.set_sequence_2_the_max(text, text) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.show(text[]) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.show(diagnostic.error) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.show(unit_testing.check_point) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.show_current_error() OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.show_error() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.show_test_errors(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.signatures(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.signatures_by_teacher_classroom(bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.signatures_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.signatures_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION assert.sqlstate_equals(text, text, diagnostic.error, text[]) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.statistics() OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.strip_tags(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.students_by_classroom(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.subjects(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.subjects_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.subjects_del(bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.subjects_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.subjects_ins(bigint, character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.subjects_list(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.subjects_lookup(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.subjects_lookup(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.subjects_sel(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.subjects_upd(bigint, bigint, bigint, character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION translate.synch() OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.system_messages_locale(utility.system_message[], integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.teachears_notes(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.teachears_notes_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.teachears_notes_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.teachears_notes_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.teachers_by_school(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.test_full_function_name() OWNER TO scuola247_supervisor;
ALTER FUNCTION diagnostic.test_function_name() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.thumbnail_default() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.time_dist(time without time zone, time without time zone) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.topics(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.topics_by_subject_classroom(bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.topics_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.topics_del(bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.topics_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.topics_ins_rid(bigint, character varying, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.topics_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.topics_upd_rid(bigint, bigint, character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_absences_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_classrooms_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_classrooms_students_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_communications_media_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.tr_continuous_integration() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_conversations_invites_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_delays_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.tr_dependencies_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_explanations_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_faults_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.tr_function_versions_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_valutations_d() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_valutations_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_valutations_qua_d() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_grading_meetings_valutations_qua_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_leavings_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_lessons_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_messages_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_messages_read_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_notes_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_notes_signed_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_out_of_classrooms_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_parents_meetings_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_schools_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_signatures_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_teachears_notes_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_topics_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.tr_unit_test_sets_details_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_usename_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_valutations_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_valutations_qualifications_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tr_weekly_timetables_days_iu() OWNER TO scuola247_supervisor;
ALTER FUNCTION translate.translation() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.ts_dist(timestamp without time zone, timestamp without time zone) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.tstz_dist(timestamp with time zone, timestamp with time zone) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.unit_tests_list_lookup(name) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_testing.unit_tests_list_lookup(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.url_decode(text) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.urlencode(character varying) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.usenames_ex(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.usenames_schools(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.usenames_schools_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.usenames_schools_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.valutations(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.valutations_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.valutations_del(bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.valutations_ex_by_classroom_teacher_subject(bigint, bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.valutations_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.valutations_ins(bigint, bigint, bigint, bigint, bigint, character varying, boolean, bigint, date) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.valutations_ins_note(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.valutations_qualifications(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.valutations_qualifications_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.valutations_qualifications_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.valutations_qualifications_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.valutations_sel(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.valutations_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.valutations_upd(bigint, bigint, character varying, boolean, boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.valutations_upd_grade(bigint, bigint, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.w_classrooms_ex() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.w_classrooms_students_ex() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.w_classrooms_teachers_subjects_ex() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.w_weekly_timetable_ex() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.w_weekly_timetables_days_ex() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.weekly_timetable_xt_subject(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.weekly_timetable_xt_teacher(bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.weekly_timetables(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.weekly_timetables_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.weekly_timetables_days(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.weekly_timetables_days_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.weekly_timetables_days_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.weekly_timetables_days_trigger(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.weekly_timetables_foreign_key(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.where_sequence(text, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION utility.where_sequence(text, text, text, bigint) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.wikimedia_0_reset() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.wikimedia_1_recreate_wikimedia_files_persons() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.wikimedia_2_wikimedia_files_hydration(integer) OWNER TO scuola247_supervisor;
ALTER FUNCTION public.wikimedia_3_wikimedia_files_popolate_files() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.wikimedia_4_persons_hydration() OWNER TO scuola247_supervisor;
ALTER FUNCTION public.wikimedia_5_persons_popolate_files() OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.wikimedia_files(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.wikimedia_files_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.wikimedia_files_persons(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.wikimedia_files_persons_check(boolean) OWNER TO scuola247_supervisor;
ALTER FUNCTION unit_tests_public.wikimedia_files_persons_foreign_key(boolean) OWNER TO scuola247_supervisor;
/* VIEWS & TABLES*/;
ALTER TABLE public.conversations_invites OWNER TO scuola247_supervisor;
ALTER TABLE public.schools OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.tests_details_ex OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.unit_tests_list OWNER TO scuola247_supervisor;
ALTER TABLE datasets.ip_addresses OWNER TO scuola247_supervisor;
ALTER TABLE datasets.apache2_conf OWNER TO scuola247_supervisor;
ALTER TABLE datasets.entity_coding OWNER TO scuola247_supervisor;
ALTER TABLE datasets.ip_addresses_country_list OWNER TO scuola247_supervisor;
ALTER TABLE diagnostic.functions_check OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.tests OWNER TO scuola247_supervisor;
ALTER TABLE translate.procedures_excluded OWNER TO scuola247_supervisor;
ALTER TABLE diagnostic.functions_list OWNER TO scuola247_supervisor;
ALTER TABLE diagnostic.views_working OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms_students_addresses_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.topics OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.information_schema_catalog_name OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.attributes OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.applicable_roles OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.administrable_role_authorizations OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.check_constraint_routine_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.character_sets OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.check_constraints OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.collations OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.collation_character_set_applicability OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.column_domain_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.column_privileges OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.routine_privileges OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.column_udt_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.columns OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.constraint_column_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.role_routine_grants OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.constraint_table_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.domain_constraints OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.domain_udt_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.routines OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.domains OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.enabled_roles OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.sql_parts OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.key_column_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.schemata OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.parameters OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.referential_constraints OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.sql_languages OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.role_column_grants OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.sequences OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.sql_features OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.sql_implementation_info OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.sql_packages OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.sql_sizing OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.sql_sizing_profiles OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.view_routine_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.table_constraints OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.table_privileges OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.foreign_table_options OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.role_table_grants OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.view_table_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.tables OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.transforms OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.triggered_update_columns OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.foreign_data_wrappers OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.triggers OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.views OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.udt_privileges OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.role_udt_grants OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.usage_privileges OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.data_type_privileges OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.role_usage_grants OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.user_defined_types OWNER TO scuola247_supervisor;
ALTER TABLE information_schema._pg_foreign_servers OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.view_column_usage OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.element_types OWNER TO scuola247_supervisor;
ALTER TABLE information_schema._pg_foreign_table_columns OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.column_options OWNER TO scuola247_supervisor;
ALTER TABLE information_schema._pg_foreign_data_wrappers OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.foreign_server_options OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.foreign_data_wrapper_options OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.user_mapping_options OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.foreign_servers OWNER TO scuola247_supervisor;
ALTER TABLE information_schema._pg_foreign_tables OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.foreign_tables OWNER TO scuola247_supervisor;
ALTER TABLE information_schema._pg_user_mappings OWNER TO scuola247_supervisor;
ALTER TABLE information_schema.user_mappings OWNER TO scuola247_supervisor;
ALTER TABLE public.persons OWNER TO scuola247_supervisor;
ALTER TABLE public.cities OWNER TO scuola247_supervisor;
ALTER TABLE public.residence_grp_city OWNER TO scuola247_supervisor;
ALTER TABLE public.persons_addresses OWNER TO scuola247_supervisor;
ALTER TABLE public.countries OWNER TO scuola247_supervisor;
ALTER TABLE public.teachears_notes OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms_teachers_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.grading_meetings_valutations_qua OWNER TO scuola247_supervisor;
ALTER TABLE public.notes_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.grades OWNER TO scuola247_supervisor;
ALTER TABLE public.grading_meetings_valutations OWNER TO scuola247_supervisor;
ALTER TABLE public.absences OWNER TO scuola247_supervisor;
ALTER TABLE public.holidays OWNER TO scuola247_supervisor;
ALTER TABLE public.branches OWNER TO scuola247_supervisor;
ALTER TABLE public.messages OWNER TO scuola247_supervisor;
ALTER TABLE public.wikimedia_license_infos OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms_students OWNER TO scuola247_supervisor;
ALTER TABLE public.wikimedia_files OWNER TO scuola247_supervisor;
ALTER TABLE public.messages_read OWNER TO scuola247_supervisor;
ALTER TABLE public.metrics OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms OWNER TO scuola247_supervisor;
ALTER TABLE public.__gb_metadata_v2 OWNER TO scuola247_supervisor;
ALTER TABLE public.out_of_classrooms OWNER TO scuola247_supervisor;
ALTER TABLE public.conversations OWNER TO scuola247_supervisor;
ALTER TABLE public._rls_test OWNER TO scuola247_supervisor;
ALTER TABLE public.test OWNER TO scuola247_supervisor;
ALTER TABLE translate.columns_to_translate OWNER TO scuola247_supervisor;
ALTER TABLE translate.relations OWNER TO scuola247_supervisor;
ALTER TABLE translate.procedures_to_translate OWNER TO scuola247_supervisor;
ALTER TABLE translate.procedures OWNER TO scuola247_supervisor;
ALTER TABLE translate.relations_excluded OWNER TO scuola247_supervisor;
ALTER TABLE translate.relations_to_translate OWNER TO scuola247_supervisor;
ALTER TABLE translate.texts_to_translate_for_procedure_and_arguments OWNER TO scuola247_supervisor;
ALTER TABLE translate.texts_to_translate_for_relations_and_columns OWNER TO scuola247_supervisor;
ALTER TABLE public._rls_test_security_barrier OWNER TO scuola247_supervisor;
ALTER TABLE translate.columns OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.last_failed_tests_details_ex OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.tests_check_points_count OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.tests_check_points_count_crosstab OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.tests_functions_count OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.tests_functions_count_crosstab OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.unit_tests_versions OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.unit_tests_run_level OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.unit_tests_circular_references OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.unit_tests_run_level_tree OWNER TO scuola247_supervisor;
ALTER TABLE utility.enums_values OWNER TO scuola247_supervisor;
ALTER TABLE utility.sequence_references OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.function_versions OWNER TO scuola247_supervisor;
ALTER TABLE public.usenames_schools OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.dependencies OWNER TO scuola247_supervisor;
ALTER TABLE public.explanations OWNER TO scuola247_supervisor;
ALTER TABLE public.leavings_not_explained_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.notes_grp OWNER TO scuola247_supervisor;
ALTER TABLE translate.languages OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.tests_details OWNER TO scuola247_supervisor;
ALTER TABLE public.out_of_classrooms_grp OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.unit_test_sets OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.unit_test_sets_details OWNER TO scuola247_supervisor;
ALTER TABLE public.weekly_timetable_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.absences_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.absences_not_explanated_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.notes OWNER TO scuola247_supervisor;
ALTER TABLE public.delays_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.delays_not_explained_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.leavings_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.subjects OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms_students_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.leavings OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms_teachers_subjects_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.weekly_timetables_days_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.absences_certified_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.absences_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.lessons OWNER TO scuola247_supervisor;
ALTER TABLE public.signatures OWNER TO scuola247_supervisor;
ALTER TABLE public.absences_month_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms_teachers OWNER TO scuola247_supervisor;
ALTER TABLE public.delays_certified_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.leavings_certified_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.lessons_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.notes_iussed_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.out_of_classrooms_certified_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.signatures_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.parents_meetings OWNER TO scuola247_supervisor;
ALTER TABLE public.classrooms_teachers_subject OWNER TO scuola247_supervisor;
ALTER TABLE public.delays OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_qualifications OWNER TO scuola247_supervisor;
ALTER TABLE public.signatures_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.out_of_classrooms_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.out_of_classrooms_month_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.schools_school_years_classrooms_weekly_timetable OWNER TO scuola247_supervisor;
ALTER TABLE public.notes_signed OWNER TO scuola247_supervisor;
ALTER TABLE public.lessons_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.lessons_days OWNER TO scuola247_supervisor;
ALTER TABLE public.faults_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.faults OWNER TO scuola247_supervisor;
ALTER TABLE public.notes_month_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.persons_relations OWNER TO scuola247_supervisor;
ALTER TABLE public.notes_signed_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.weekly_timetables OWNER TO scuola247_supervisor;
ALTER TABLE public.delays_month_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.leavings_month_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.classbooks_month_grp OWNER TO scuola247_supervisor;
ALTER TABLE public.grade_types OWNER TO scuola247_supervisor;
ALTER TABLE public.delays_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.weekly_timetables_days OWNER TO scuola247_supervisor;
ALTER TABLE public.communication_types OWNER TO scuola247_supervisor;
ALTER TABLE public.qualifications_plan OWNER TO scuola247_supervisor;
ALTER TABLE public.leavings_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.qualifications OWNER TO scuola247_supervisor;
ALTER TABLE public.wikimedia_files_persons OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.communications_media OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_references OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_ex_references OWNER TO scuola247_supervisor;
ALTER TABLE public.grading_meetings OWNER TO scuola247_supervisor;
ALTER TABLE public.degrees OWNER TO scuola247_supervisor;
ALTER TABLE public.usenames_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_stats_classrooms_students_subjects OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_stats_classrooms_subjects OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_stats_classrooms_subjects_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.districts OWNER TO scuola247_supervisor;
ALTER TABLE public._rls_test_with_check_local OWNER TO scuola247_supervisor;
ALTER TABLE public._rls_test_with_check_local_cascade OWNER TO scuola247_supervisor;
ALTER TABLE public.teachers_classbooks_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.teachers_lessons_signatures_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.usenames_rolnames OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_stats_classrooms_students_subjects_on_date OWNER TO scuola247_supervisor;
ALTER TABLE public.valutations_stats_classrooms_students_subjects_on_date_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.weekly_timetable_teachers_ex OWNER TO scuola247_supervisor;
ALTER TABLE public.persons_roles OWNER TO scuola247_supervisor;
ALTER TABLE public.regions OWNER TO scuola247_supervisor;
ALTER TABLE public.school_years OWNER TO scuola247_supervisor;


/* SEQUENCES */;

ALTER TABLE datasets.pk_seq OWNER TO scuola247_supervisor;
ALTER TABLE translate.pk_seq OWNER TO scuola247_supervisor;
ALTER TABLE public.pk_seq OWNER TO scuola247_supervisor;
ALTER TABLE unit_testing.pk_seq OWNER TO scuola247_supervisor;