-- Function: unit_tests.countries(boolean)

-- DROP FUNCTION unit_tests.countries(boolean);

CREATE OR REPLACE FUNCTION unit_tests.countries(
    IN _build_dependencies boolean DEFAULT false,
    OUT _results unit_testing.unit_test_result[])
  RETURNS unit_testing.unit_test_result[] AS
$BODY$

<<me>>
DECLARE 
  context               text;
  full_function_name 	text;
  test_name		text = '';
  error			diagnostic.error;
BEGIN
  GET DIAGNOSTICS context = PG_CONTEXT;
  full_function_name = diagnostic.full_function_name(context);
  -- check to build dependencies
  IF _build_dependencies THEN
    PERFORM unit_testing.build_function_dependencies(diagnostic.function_name(context));
    RETURN;
  END IF;  
  -------------------------------
  test_name = 'INSERT countries';
  -------------------------------
  BEGIN
    /*
    INSERT INTO public.countries(country,description,existing) VALUES ('201','BELGIO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('202','DANIMARCA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('203','FRANCIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('204','GRECIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('205','IRLANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('206','LUSSEMBURGO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('207','PAESI BASSI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('208','PORTOGALLO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('211','SPAGNA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('220','ALBANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('221','AUSTRIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('222','BULGARIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('223','CECA, REPUBBLICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('224','SLOVACCHIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('225','FINLANDIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('228','MALTA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('229','NORVEGIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('233','SAN MARINO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('234','SVEZIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('235','SVIZZERA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('236','TURCHIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('237','UNGHERIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('242','MACEDONIA, EX REPUBBLICA JUGOSLAVA DI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('243','BOSNIA ED ERZEGOVINA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('244','CROAZIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('245','SLOVENIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('246','ARMENIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('247','AZERBAIGIAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('248','GEORGIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('249','KIRGHIZISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('251','UZBEKISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('253','TAGIKISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('254','TURKMENISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('255','BIELORUSSIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('256','UCRAINA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('257','KAZAKISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('260','LETTONIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('261','LITUANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('209','REGNO UNITO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('210','GERMANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('230','POLONIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('232','ROMANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('250','MOLDAVIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('252','RUSSA, FEDERAZIONE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('304','MAROCCO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('263','ESTONIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('317','NIGER','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('441','BOLIVIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('442','BRASILE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('529','SRI LANKA (EX CEYLON)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('530','INDIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('266','ISLANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('270','ANDORRA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('271','CITTA'' DEL VATICANO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('272','LIECHTENSTEIN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('273','MONACO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('301','ALGERIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('302','EGITTO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('303','LIBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('305','SUDAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('306','TUNISIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('307','GUINEA BISSAU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('309','SIERRA LEONE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('310','BURKINA FASO (EX ALTO VOLTA)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('311','CIAD','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('312','COSTA D''AVORIO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('313','GHANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('314','GUINEA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('315','MALI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('316','NIGERIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('318','CAPO VERDE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('319','SENEGAL','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('320','REPUBBLICA SUDAFRICANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('321','LIBERIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('322','SWAZILAND','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('323','BURUNDI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('328','SEICELLE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('329','MAURITIUS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('330','ANGOLA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('331','CAMERUN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('332','ETIOPIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('333','COMORE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('334','MADAGASCAR','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('335','MALAWI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('336','KENYA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('337','MOZAMBICO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('338','LESOTHO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('339','RUANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('340','SOMALIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('341','TANZANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('342','UGANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('343','CONGO, REPUBBLICA DEMOCRATICA DEL (EX ZAIRE)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('344','ZAMBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('345','ZIMBABWE (EX RHODESIA)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('347','MAURITANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('348','GAMBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('349','BENIN (EX DAHOMEY)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('350','TOGO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('351','BOTSWANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('352','CENTRAFRICANA REPUBBLICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('353','CONGO, REPUBBLICA POPOLARE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('354','ERITREA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('355','SAO TOME'' E PRINCIPE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('356','GIBUTI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('357','NAMIBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('358','GUINEA EQUATORIALE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('359','GABON','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('401','CANADA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('402','STATI UNITI D''AMERICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('403','REPUBBLICA DELLA GUAYANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('404','SURINAME','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('405','BARBADOS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('410','COSTA RICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('411','CUBA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('412','EL SALVADOR','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('413','GIAMAICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('414','GUATEMALA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('415','HAITI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('416','HONDURAS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('417','MESSICO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('418','NICARAGUA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('419','PANAMA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('420','REPUBBLICA DOMINICANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('428','BELIZE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('440','ARGENTINA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('443','CILE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('444','COLOMBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('445','ECUADOR','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('446','PARAGUAY','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('447','PERU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('449','URUGUAY','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('450','VENEZUELA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('460','ANTIGUA E BARBUDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('461','BAHAMA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('462','DOMINICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('463','GRENADA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('464','SAINT VINCENT E GRENADINE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('465','SAINT KITTS E NEVIS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('466','SAINT LUCIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('498','TRINIDAD E TOBAGO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('500','PALESTINA (TERRITORI DELL''AUTONOMIA PALESTINESE)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('501','ARABIA SAUDITA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('502','CIPRO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('503','GIORDANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('504','IRAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('505','IRAQ','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('506','ISRAELE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('507','LIBANO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('508','SIRIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('509','YEMEN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('510','AFGHANISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('519','CAMBOGIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('520','BANGLADESH','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('521','BHUTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('522','MYANMAR (EX BIRMANIA)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('523','LAOS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('524','CINA REPUBBLICA POPOLARE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('525','COREA, REPUBBLICA POPOLARE DEMOCRATICA (COREA DEL NORD)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('526','COREA, REPUBBLICA (COREA DEL SUD)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('527','FILIPPINE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('528','GIAPPONE GIAPPONE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('531','BRUNEI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('532','INDONESIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('533','NEPAL','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('534','PAKISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('535','MALDIVE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('536','THAILANDIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('537','TAIWAN (EX FORMOSA)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('538','VIETNAM','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('551','KUWAIT','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('552','MONGOLIA REP. POPOLARE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('553','SINGAPORE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('560','BAHEREIN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('561','EMIRATI ARABI UNITI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('562','OMAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('563','QATAR','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('600','MARSHALL, ISOLE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('601','AUSTRALIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('602','NUOVA ZELANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('603','FIGI O VITI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('604','KIRIBATI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('605','PAPUA NUOVA GUINEA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('606','SALOMONE, ISOLE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('607','SAMOA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('608','TONGA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('609','TUVALU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('610','MICRONESIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('611','NAURU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('612','PALAU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('613','VANUATU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('700','APOLIDI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('701','MONTENEGRO ONTENEGRO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('702','SERBIA,REPUBBLICA DI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('709','KOSOVO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('731','MALAYSIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('227','IUGOSLAVIA (fino al 04/02/2003)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('231','GROENLANDIA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('238','URSS (fino al 31/03/1992)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('241','SERBIA E MONTENEGRO (fino al 02/06/2006)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('468','ISOLE VERGINI USA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('470','ISOLE VERGINI B. E MONTSERRAT','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('471','ISOLE CAYMAN','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('472','ISOLE TURKS E CAICOS','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('474','PUERTO RICO','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('477','BERMUDE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('515','MALESIA (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('516','HONG KONG (fino al01/07/1997)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('518','MACAO','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('704','TIMOR ORIENTALE (fino al 31/12/1978)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('705','CECOSLOVACCHIA (fino al 01/01/1993)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('706','DIPENDENZE SOVIETICHE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('707','GERMANIA REPUBBLICA DEMOCRATICA (fino al 03/10/1990)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('708','GUAYANA FRANCESE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('711','TERRITORIO DI GAZA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('712','FAER OER (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('713','GIBILTERRA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('714','MAN (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('715','NORMANNE (ISOLE)=ISOLE DEL CANALE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('716','GEORGIA (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('717','ARMENIA (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('718','AZERBAIGIAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('719','KIRGHIZISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('720','UZBEKISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('721','TAGIKISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('722','TURKEMENISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('723','KAZAKISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('724','ARABIA MERIDIONALE FEDERAZIONE (fino al 31/12/1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('725','ARABIA MERIDIONALE PROTETTORATO (fino al 31/12/1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('726','COCOS (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('727','RYUKYU ISOLE (fino al 31/12/1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('728','SIKKIM (fino al 31/12/1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('729','VIETNAM DEL SUD (fino al 31/12/1977)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('730','VIETNAM DEL NORD (fino al 31/12/1977)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('732','YEMEN REPUBBLICA DEMOCRATICA POPOLARE (fino al 22/05/1990)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('733','BASUTOLAND-SUD AFRICA BRITANNICO (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('734','BECIUANIA-SUD AFRICA BRITANNICO (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('735','IFNI (fino al 31/12/1984)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('736','LA REUNION (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('737','SAHARA SPAGNOLO (fino al 31/12/1977)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('738','SANT''ELENA (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('739','TERR. FRANCESE DEGLI AFAR E DEGLI ISSA (fino al 31/12/1977)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('740','TANGANICA (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('741','ZANZIBAR (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('742','MAYOTTE (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('743','SAHARA MERIDIONALE (fino al 31/12/1984)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('744','SAHARA SETTENTRIONALE (fino al 31/12/1984)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('745','BOPHUTHATSWANA (fino al 01/01/1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('746','TRANSKEI (fino al 01/01/1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('747','VENDA (fino al 01/01/1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('748','CISKEI (fino al 01/01/1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('749','NYASALAND (fino al 05/07/1964)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('750','CONGO BELGA (fino al 01/01/1960)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('751','SAINT PIERRE ET MIQUELON (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('752','ANTILLE BRITANNICHE (fino al 31.12.1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('753','ANTILLE OLANDESI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('754','GUADALUPA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('755','MARTINICA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('756','ANTILLE BRITANNICHE (fino 31/12/1984)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('757','ANGUILLA (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('758','MONTSERRAT','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('759','MALVINE=FALKLAND (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('760','CAROLINE (ISOLE)=STATI FEDERATI DI MICRONESIA (22/12/1990)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('761','CHRISTMAS (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('762','COOK (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('763','GILBERT E ELLICE ISOLE (fino al 3/12/1980)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('764','GUAM (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('765','IRIAN OCCIDENTALE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('766','MACQUARIE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('767','MARCUS ISOLE (fino al 31.12.1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('768','MARIANNE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('769','MIDWAY (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('770','NIUE=SAVAGE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('771','NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('772','NUOVA CALEDONIA (ISOLE E DIPENDENZE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('773','NUOVE EBRIDI CONDOMINIO FRANCO-INGLESE (fino al 31.12.1980)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('774','NUOVA GUINEA (fino al 31.12.1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('775','PAPUASIA (fino al 31.12.1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('776','ISOLE CILENE (PASQUA E SALA Y GOMEZ)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('777','PITCAIRN (E DIPENDENZE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('778','POLINESIA FRANCESE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('779','SAMOA AMERICANE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('780','TOKELAU=ISOLE DELL''UNIONE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('781','WALLIS E FUTUNA (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('782','DIPENDENZE CANADESI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('783','DIPENDENZE NORVEGESI ARTICHE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('784','DIPENDENZE AUSTRALIANE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('785','DIPENDENZE BRITANNICHE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('786','DIPENDENZE FRANCESI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('787','DIPENDENZE NEOZELANDESI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('788','DIPENDENZE NORVEGESI ANTARTICHE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('789','DIPENDENZE STATUNITENSI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('790','DIPENDENZE SUDAFRICANE DIPENDENZE SUDAFRICANE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('200','ITALIA','f');
    */

    _results = _results || assert.pass(full_function_name, test_name);

    EXCEPTION
       WHEN OTHERS THEN 
         GET STACKED DIAGNOSTICS error.returned_sqlstate = RETURNED_SQLSTATE, error.message_text = MESSAGE_TEXT, error.schema_name = SCHEMA_NAME, error.table_name = TABLE_NAME, error.column_name = COLUMN_NAME, error.constraint_name = CONSTRAINT_NAME, error.pg_exception_context = PG_EXCEPTION_CONTEXT, error.pg_exception_detail = PG_EXCEPTION_DETAIL, error.pg_exception_hint = PG_EXCEPTION_HINT, error.pg_datatype_name = PG_DATATYPE_NAME;
         _results = _results || assert.fail(full_function_name, test_name, 'INSERT public.countries FAILED'::text, error);   
       RETURN; 
  END;
  RETURN; 
END

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION unit_tests.countries(boolean)
  OWNER TO postgres;
