INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('201','BELGIO','t','201');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('202','DANIMARCA','t','202');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('203','FRANCIA','t','203');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('204','GRECIA','t','204');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('205','IRLANDA','t','205');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('206','LUSSEMBURGO','t','206');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('207','PAESI BASSI','t','207');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('208','PORTOGALLO','t','208');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('211','SPAGNA','t','211');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('220','ALBANIA','t','220');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('221','AUSTRIA','t','221');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('222','BULGARIA','t','222');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('223','CECA, REPUBBLICA','t','223');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('224','SLOVACCHIA','t','224');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('225','FINLANDIA','t','225');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('228','MALTA','t','228');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('229','NORVEGIA','t','229');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('233','SAN MARINO','t','233');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('234','SVEZIA','t','234');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('235','SVIZZERA','t','235');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('236','TURCHIA','t','236');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('237','UNGHERIA','t','237');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('242','MACEDONIA, EX REPUBBLICA JUGOSLAVA DI','t','242');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('243','BOSNIA ED ERZEGOVINA','t','243');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('244','CROAZIA','t','244');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('245','SLOVENIA','t','245');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('246','ARMENIA','t','246');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('247','AZERBAIGIAN','t','247');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('248','GEORGIA','t','248');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('249','KIRGHIZISTAN','t','249');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('251','UZBEKISTAN','t','251');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('253','TAGIKISTAN','t','253');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('254','TURKMENISTAN','t','254');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('255','BIELORUSSIA','t','255');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('256','UCRAINA','t','256');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('257','KAZAKISTAN','t','257');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('260','LETTONIA','t','260');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('261','LITUANIA','t','261');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('209','REGNO UNITO','t','209');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('210','GERMANIA','t','210');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('230','POLONIA','t','230');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('232','ROMANIA','t','232');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('250','MOLDAVIA','t','250');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('252','RUSSA, FEDERAZIONE','t','252');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('304','MAROCCO','t','304');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('263','ESTONIA','t','263');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('317','NIGER','t','317');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('441','BOLIVIA','t','441');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('442','BRASILE','t','442');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('529','SRI LANKA (EX CEYLON)','t','529');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('530','INDIA','t','530');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('266','ISLANDA','t','266');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('270','ANDORRA','t','270');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('271','CITTA'' DEL VATICANO','t','271');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('272','LIECHTENSTEIN','t','272');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('273','MONACO','t','273');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('301','ALGERIA','t','301');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('302','EGITTO','t','302');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('303','LIBIA','t','303');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('305','SUDAN','t','305');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('306','TUNISIA','t','306');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('307','GUINEA BISSAU','t','307');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('309','SIERRA LEONE','t','309');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('310','BURKINA FASO (EX ALTO VOLTA)','t','310');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('311','CIAD','t','311');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('312','COSTA D''AVORIO','t','312');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('313','GHANA','t','313');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('314','GUINEA','t','314');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('315','MALI','t','315');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('316','NIGERIA','t','316');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('318','CAPO VERDE','t','318');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('319','SENEGAL','t','319');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('320','REPUBBLICA SUDAFRICANA','t','320');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('321','LIBERIA','t','321');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('322','SWAZILAND','t','322');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('323','BURUNDI','t','323');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('328','SEICELLE','t','328');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('329','MAURITIUS','t','329');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('330','ANGOLA','t','330');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('331','CAMERUN','t','331');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('332','ETIOPIA','t','332');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('333','COMORE','t','333');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('334','MADAGASCAR','t','334');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('335','MALAWI','t','335');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('336','KENYA','t','336');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('337','MOZAMBICO','t','337');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('338','LESOTHO','t','338');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('339','RUANDA','t','339');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('340','SOMALIA','t','340');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('341','TANZANIA','t','341');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('342','UGANDA','t','342');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('343','CONGO, REPUBBLICA DEMOCRATICA DEL (EX ZAIRE)','t','343');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('344','ZAMBIA','t','344');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('345','ZIMBABWE (EX RHODESIA)','t','345');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('347','MAURITANIA','t','347');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('348','GAMBIA','t','348');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('349','BENIN (EX DAHOMEY)','t','349');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('350','TOGO','t','350');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('351','BOTSWANA','t','351');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('352','CENTRAFRICANA REPUBBLICA','t','352');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('353','CONGO, REPUBBLICA POPOLARE','t','353');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('354','ERITREA','t','354');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('355','SAO TOME'' E PRINCIPE','t','355');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('356','GIBUTI','t','356');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('357','NAMIBIA','t','357');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('358','GUINEA EQUATORIALE','t','358');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('359','GABON','t','359');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('401','CANADA','t','401');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('402','STATI UNITI D''AMERICA','t','402');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('403','REPUBBLICA DELLA GUAYANA','t','403');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('404','SURINAME','t','404');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('405','BARBADOS','t','405');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('410','COSTA RICA','t','410');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('411','CUBA','t','411');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('412','EL SALVADOR','t','412');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('413','GIAMAICA','t','413');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('414','GUATEMALA','t','414');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('415','HAITI','t','415');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('416','HONDURAS','t','416');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('417','MESSICO','t','417');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('418','NICARAGUA','t','418');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('419','PANAMA','t','419');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('420','REPUBBLICA DOMINICANA','t','420');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('428','BELIZE','t','428');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('440','ARGENTINA','t','440');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('443','CILE','t','443');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('444','COLOMBIA','t','444');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('445','ECUADOR','t','445');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('446','PARAGUAY','t','446');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('447','PERU','t','447');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('449','URUGUAY','t','449');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('450','VENEZUELA','t','450');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('460','ANTIGUA E BARBUDA','t','460');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('461','BAHAMA','t','461');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('462','DOMINICA','t','462');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('463','GRENADA','t','463');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('464','SAINT VINCENT E GRENADINE','t','464');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('465','SAINT KITTS E NEVIS','t','465');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('466','SAINT LUCIA','t','466');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('498','TRINIDAD E TOBAGO','t','498');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('500','PALESTINA (TERRITORI DELL''AUTONOMIA PALESTINESE)','t','500');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('501','ARABIA SAUDITA','t','501');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('502','CIPRO','t','502');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('503','GIORDANIA','t','503');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('504','IRAN','t','504');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('505','IRAQ','t','505');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('506','ISRAELE','t','506');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('507','LIBANO','t','507');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('508','SIRIA','t','508');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('509','YEMEN','t','509');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('510','AFGHANISTAN','t','510');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('519','CAMBOGIA','t','519');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('520','BANGLADESH','t','520');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('521','BHUTAN','t','521');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('522','MYANMAR (EX BIRMANIA)','t','522');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('523','LAOS','t','523');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('524','CINA REPUBBLICA POPOLARE','t','524');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('525','COREA, REPUBBLICA POPOLARE DEMOCRATICA (COREA DEL NORD)','t','525');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('526','COREA, REPUBBLICA (COREA DEL SUD)','t','526');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('527','FILIPPINE','t','527');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('528','GIAPPONE GIAPPONE','t','528');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('531','BRUNEI','t','531');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('532','INDONESIA','t','532');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('533','NEPAL','t','533');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('534','PAKISTAN','t','534');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('535','MALDIVE','t','535');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('536','THAILANDIA','t','536');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('537','TAIWAN (EX FORMOSA)','t','537');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('538','VIETNAM','t','538');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('551','KUWAIT','t','551');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('552','MONGOLIA REP. POPOLARE','t','552');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('553','SINGAPORE','t','553');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('560','BAHEREIN','t','560');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('561','EMIRATI ARABI UNITI','t','561');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('562','OMAN','t','562');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('563','QATAR','t','563');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('600','MARSHALL, ISOLE','t','600');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('601','AUSTRALIA','t','601');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('602','NUOVA ZELANDA','t','602');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('603','FIGI O VITI','t','603');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('604','KIRIBATI','t','604');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('605','PAPUA NUOVA GUINEA','t','605');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('606','SALOMONE, ISOLE','t','606');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('607','SAMOA','t','607');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('608','TONGA','t','608');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('609','TUVALU','t','609');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('610','MICRONESIA','t','610');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('611','NAURU','t','611');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('612','PALAU','t','612');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('613','VANUATU','t','613');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('700','APOLIDI','t','700');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('701','MONTENEGRO ONTENEGRO','t','701');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('702','SERBIA,REPUBBLICA DI','t','702');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('709','KOSOVO','t','709');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('731','MALAYSIA','t','731');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('227','IUGOSLAVIA (fino al 04/02/2003)','f','227');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('231','GROENLANDIA','f','231');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('238','URSS (fino al 31/03/1992)','f','238');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('241','SERBIA E MONTENEGRO (fino al 02/06/2006)','f','241');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('468','ISOLE VERGINI USA','f','468');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('470','ISOLE VERGINI B. E MONTSERRAT','f','470');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('471','ISOLE CAYMAN','f','471');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('472','ISOLE TURKS E CAICOS','f','472');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('474','PUERTO RICO','f','474');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('477','BERMUDE','f','477');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('515','MALESIA (fino al 01/10/1966)','f','515');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('516','HONG KONG (fino al01/07/1997)','f','516');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('518','MACAO','f','518');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('704','TIMOR ORIENTALE (fino al 31/12/1978)','f','704');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('705','CECOSLOVACCHIA (fino al 01/01/1993)','f','705');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('706','DIPENDENZE SOVIETICHE','f','706');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('707','GERMANIA REPUBBLICA DEMOCRATICA (fino al 03/10/1990)','f','707');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('708','GUAYANA FRANCESE','f','708');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('711','TERRITORIO DI GAZA','f','711');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('712','FAER OER (ISOLE)','f','712');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('713','GIBILTERRA','f','713');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('714','MAN (ISOLA)','f','714');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('715','NORMANNE (ISOLE)=ISOLE DEL CANALE','f','715');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('716','GEORGIA (fino al 01.01.1994)','f','716');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('717','ARMENIA (fino al 01.01.1994)','f','717');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('718','AZERBAIGIAN (fino al 01.01.1994)','f','718');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('719','KIRGHIZISTAN (fino al 01.01.1994)','f','719');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('720','UZBEKISTAN (fino al 01.01.1994)','f','720');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('721','TAGIKISTAN (fino al 01.01.1994)','f','721');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('722','TURKEMENISTAN (fino al 01.01.1994)','f','722');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('723','KAZAKISTAN (fino al 01.01.1994)','f','723');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('724','ARABIA MERIDIONALE FEDERAZIONE (fino al 31/12/1975)','f','724');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('725','ARABIA MERIDIONALE PROTETTORATO (fino al 31/12/1975)','f','725');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('726','COCOS (ISOLE)','f','726');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('727','RYUKYU ISOLE (fino al 31/12/1975)','f','727');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('728','SIKKIM (fino al 31/12/1975)','f','728');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('729','VIETNAM DEL SUD (fino al 31/12/1977)','f','729');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('730','VIETNAM DEL NORD (fino al 31/12/1977)','f','730');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('732','YEMEN REPUBBLICA DEMOCRATICA POPOLARE (fino al 22/05/1990)','f','732');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('733','BASUTOLAND-SUD AFRICA BRITANNICO (fino al 01/10/1966)','f','733');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('734','BECIUANIA-SUD AFRICA BRITANNICO (fino al 01/10/1966)','f','734');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('735','IFNI (fino al 31/12/1984)','f','735');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('736','LA REUNION (ISOLA)','f','736');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('737','SAHARA SPAGNOLO (fino al 31/12/1977)','f','737');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('738','SANT''ELENA (ISOLA)','f','738');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('739','TERR. FRANCESE DEGLI AFAR E DEGLI ISSA (fino al 31/12/1977)','f','739');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('740','TANGANICA (fino al 01/10/1966)','f','740');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('741','ZANZIBAR (fino al 01/10/1966)','f','741');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('742','MAYOTTE (ISOLA)','f','742');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('743','SAHARA MERIDIONALE (fino al 31/12/1984)','f','743');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('744','SAHARA SETTENTRIONALE (fino al 31/12/1984)','f','744');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('745','BOPHUTHATSWANA (fino al 01/01/1994)','f','745');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('746','TRANSKEI (fino al 01/01/1994)','f','746');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('747','VENDA (fino al 01/01/1994)','f','747');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('748','CISKEI (fino al 01/01/1994)','f','748');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('749','NYASALAND (fino al 05/07/1964)','f','749');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('750','CONGO BELGA (fino al 01/01/1960)','f','750');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('751','SAINT PIERRE ET MIQUELON (ISOLE)','f','751');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('752','ANTILLE BRITANNICHE (fino al 31.12.1975)','f','752');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('753','ANTILLE OLANDESI','f','753');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('754','GUADALUPA','f','754');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('755','MARTINICA','f','755');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('756','ANTILLE BRITANNICHE (fino 31/12/1984)','f','756');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('757','ANGUILLA (ISOLA)','f','757');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('758','MONTSERRAT','f','758');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('759','MALVINE=FALKLAND (ISOLE)','f','759');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('760','CAROLINE (ISOLE)=STATI FEDERATI DI MICRONESIA (22/12/1990)','f','760');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('761','CHRISTMAS (ISOLA)','f','761');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('762','COOK (ISOLE)','f','762');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('763','GILBERT E ELLICE ISOLE (fino al 3/12/1980)','f','763');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('764','GUAM (ISOLA)','f','764');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('765','IRIAN OCCIDENTALE','f','765');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('766','MACQUARIE (ISOLE)','f','766');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('767','MARCUS ISOLE (fino al 31.12.1975)','f','767');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('768','MARIANNE (ISOLE)','f','768');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('769','MIDWAY (ISOLE)','f','769');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('770','NIUE=SAVAGE (ISOLE)','f','770');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('771','NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)','f','771');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('772','NUOVA CALEDONIA (ISOLE E DIPENDENZE)','f','772');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('773','NUOVE EBRIDI CONDOMINIO FRANCO-INGLESE (fino al 31.12.1980)','f','773');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('774','NUOVA GUINEA (fino al 31.12.1975)','f','774');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('775','PAPUASIA (fino al 31.12.1975)','f','775');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('776','ISOLE CILENE (PASQUA E SALA Y GOMEZ)','f','776');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('777','PITCAIRN (E DIPENDENZE)','f','777');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('778','POLINESIA FRANCESE (ISOLE)','f','778');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('779','SAMOA AMERICANE (ISOLE)','f','779');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('780','TOKELAU=ISOLE DELL''UNIONE','f','780');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('781','WALLIS E FUTUNA (ISOLE)','f','781');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('782','DIPENDENZE CANADESI','f','782');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('783','DIPENDENZE NORVEGESI ARTICHE','f','783');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('784','DIPENDENZE AUSTRALIANE','f','784');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('785','DIPENDENZE BRITANNICHE','f','785');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('786','DIPENDENZE FRANCESI','f','786');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('787','DIPENDENZE NEOZELANDESI','f','787');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('788','DIPENDENZE NORVEGESI ANTARTICHE','f','788');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('789','DIPENDENZE STATUNITENSI','f','789');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('790','DIPENDENZE SUDAFRICANE DIPENDENZE SUDAFRICANE','f','790');
INSERT INTO shared.countries(country,description,existing,processing_code) VALUES ('200','ITALIA','f','200');
