format
INSERT INTO public.regions(region,description,geographical_area) VALUES ('1000000000','Piemonte (test)','North-west');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('2000000000','Valle d''Aosta/Vallée d''Aoste (test)','North-west');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('3000000000','Lombardia (test)','North-west');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('4000000000','Trentino-Alto Adige/Südtirol (test)','North-east');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('5000000000','Veneto (test)','North-east');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('6000000000','Friuli-Venezia Giulia (test)','North-east');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('7000000000','Liguria (test)','North-west');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('8000000000','Emilia-Romagna (test)','North-east');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('9000000000','Toscana (test)','Center');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('10000000000','Umbria (test)','Center');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('11000000000','Marche (test)','Center');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('12000000000','Lazio (test)','Center');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('13000000000','Abruzzo (test)','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('14000000000','Molise (test)','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('15000000000','Campania (test)','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('16000000000','Puglia (test)','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('17000000000','Basilicata (test)','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('18000000000','Calabria (test)','South');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('19000000000','Sicilia (test)','Islands');
INSERT INTO public.regions(region,description,geographical_area) VALUES ('20000000000','Sardegna (test)','Islands');
