-- Function: unit_tests_public.countries(boolean)

-- DROP FUNCTION unit_tests_public.countries(boolean);

CREATE OR REPLACE FUNCTION unit_tests_public.countries(
    IN _build_dependencies boolean DEFAULT false,
    OUT _results unit_testing.unit_test_result[])
  RETURNS unit_testing.unit_test_result[] AS
$BODY$
<<me>>
DECLARE 
  context               text;
  full_function_name 	text;
  test_name		text = '';
  error			diagnostic.error;
BEGIN
  GET DIAGNOSTICS context = PG_CONTEXT;
  full_function_name = diagnostic.full_function_name(context);
  -- check to build dependencies
  IF _build_dependencies THEN
    PERFORM unit_testing.build_function_dependencies(diagnostic.function_name(context));
    RETURN;
  END IF;  
  -------------------------------
  test_name = 'INSERT countries';
  -------------------------------
  BEGIN
    /*
    INSERT INTO public.countries(country,description,existing) VALUES ('201','BELGIO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('202','DANIMARCA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('203','FRANCIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('204','GRECIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('205','IRLANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('206','LUSSEMBURGO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('207','PAESI BASSI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('208','PORTOGALLO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('211','SPAGNA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('220','ALBANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('221','AUSTRIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('222','BULGARIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('223','CECA, REPUBBLICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('224','SLOVACCHIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('225','FINLANDIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('228','MALTA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('229','NORVEGIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('233','SAN MARINO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('234','SVEZIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('235','SVIZZERA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('236','TURCHIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('237','UNGHERIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('242','MACEDONIA, EX REPUBBLICA JUGOSLAVA DI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('243','BOSNIA ED ERZEGOVINA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('244','CROAZIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('245','SLOVENIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('246','ARMENIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('247','AZERBAIGIAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('248','GEORGIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('249','KIRGHIZISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('251','UZBEKISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('253','TAGIKISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('254','TURKMENISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('255','BIELORUSSIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('256','UCRAINA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('257','KAZAKISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('260','LETTONIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('261','LITUANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('209','REGNO UNITO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('210','GERMANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('230','POLONIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('232','ROMANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('250','MOLDAVIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('252','RUSSA, FEDERAZIONE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('304','MAROCCO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('263','ESTONIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('317','NIGER','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('441','BOLIVIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('442','BRASILE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('529','SRI LANKA (EX CEYLON)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('530','INDIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('266','ISLANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('270','ANDORRA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('271','CITTA'' DEL VATICANO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('272','LIECHTENSTEIN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('273','MONACO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('301','ALGERIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('302','EGITTO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('303','LIBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('305','SUDAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('306','TUNISIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('307','GUINEA BISSAU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('309','SIERRA LEONE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('310','BURKINA FASO (EX ALTO VOLTA)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('311','CIAD','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('312','COSTA D''AVORIO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('313','GHANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('314','GUINEA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('315','MALI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('316','NIGERIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('318','CAPO VERDE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('319','SENEGAL','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('320','REPUBBLICA SUDAFRICANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('321','LIBERIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('322','SWAZILAND','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('323','BURUNDI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('328','SEICELLE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('329','MAURITIUS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('330','ANGOLA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('331','CAMERUN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('332','ETIOPIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('333','COMORE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('334','MADAGASCAR','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('335','MALAWI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('336','KENYA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('337','MOZAMBICO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('338','LESOTHO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('339','RUANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('340','SOMALIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('341','TANZANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('342','UGANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('343','CONGO, REPUBBLICA DEMOCRATICA DEL (EX ZAIRE)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('344','ZAMBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('345','ZIMBABWE (EX RHODESIA)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('347','MAURITANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('348','GAMBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('349','BENIN (EX DAHOMEY)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('350','TOGO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('351','BOTSWANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('352','CENTRAFRICANA REPUBBLICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('353','CONGO, REPUBBLICA POPOLARE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('354','ERITREA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('355','SAO TOME'' E PRINCIPE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('356','GIBUTI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('357','NAMIBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('358','GUINEA EQUATORIALE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('359','GABON','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('401','CANADA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('402','STATI UNITI D''AMERICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('403','REPUBBLICA DELLA GUAYANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('404','SURINAME','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('405','BARBADOS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('410','COSTA RICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('411','CUBA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('412','EL SALVADOR','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('413','GIAMAICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('414','GUATEMALA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('415','HAITI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('416','HONDURAS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('417','MESSICO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('418','NICARAGUA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('419','PANAMA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('420','REPUBBLICA DOMINICANA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('428','BELIZE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('440','ARGENTINA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('443','CILE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('444','COLOMBIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('445','ECUADOR','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('446','PARAGUAY','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('447','PERU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('449','URUGUAY','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('450','VENEZUELA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('460','ANTIGUA E BARBUDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('461','BAHAMA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('462','DOMINICA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('463','GRENADA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('464','SAINT VINCENT E GRENADINE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('465','SAINT KITTS E NEVIS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('466','SAINT LUCIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('498','TRINIDAD E TOBAGO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('500','PALESTINA (TERRITORI DELL''AUTONOMIA PALESTINESE)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('501','ARABIA SAUDITA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('502','CIPRO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('503','GIORDANIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('504','IRAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('505','IRAQ','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('506','ISRAELE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('507','LIBANO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('508','SIRIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('509','YEMEN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('510','AFGHANISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('519','CAMBOGIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('520','BANGLADESH','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('521','BHUTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('522','MYANMAR (EX BIRMANIA)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('523','LAOS','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('524','CINA REPUBBLICA POPOLARE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('525','COREA, REPUBBLICA POPOLARE DEMOCRATICA (COREA DEL NORD)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('526','COREA, REPUBBLICA (COREA DEL SUD)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('527','FILIPPINE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('528','GIAPPONE GIAPPONE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('531','BRUNEI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('532','INDONESIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('533','NEPAL','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('534','PAKISTAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('535','MALDIVE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('536','THAILANDIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('537','TAIWAN (EX FORMOSA)','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('538','VIETNAM','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('551','KUWAIT','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('552','MONGOLIA REP. POPOLARE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('553','SINGAPORE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('560','BAHEREIN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('561','EMIRATI ARABI UNITI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('562','OMAN','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('563','QATAR','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('600','MARSHALL, ISOLE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('601','AUSTRALIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('602','NUOVA ZELANDA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('603','FIGI O VITI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('604','KIRIBATI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('605','PAPUA NUOVA GUINEA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('606','SALOMONE, ISOLE','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('607','SAMOA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('608','TONGA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('609','TUVALU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('610','MICRONESIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('611','NAURU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('612','PALAU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('613','VANUATU','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('700','APOLIDI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('701','MONTENEGRO ONTENEGRO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('702','SERBIA,REPUBBLICA DI','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('709','KOSOVO','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('731','MALAYSIA','t');
    INSERT INTO public.countries(country,description,existing) VALUES ('227','IUGOSLAVIA (fino al 04/02/2003)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('231','GROENLANDIA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('238','URSS (fino al 31/03/1992)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('241','SERBIA E MONTENEGRO (fino al 02/06/2006)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('468','ISOLE VERGINI USA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('470','ISOLE VERGINI B. E MONTSERRAT','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('471','ISOLE CAYMAN','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('472','ISOLE TURKS E CAICOS','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('474','PUERTO RICO','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('477','BERMUDE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('515','MALESIA (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('516','HONG KONG (fino al01/07/1997)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('518','MACAO','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('704','TIMOR ORIENTALE (fino al 31/12/1978)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('705','CECOSLOVACCHIA (fino al 01/01/1993)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('706','DIPENDENZE SOVIETICHE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('707','GERMANIA REPUBBLICA DEMOCRATICA (fino al 03/10/1990)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('708','GUAYANA FRANCESE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('711','TERRITORIO DI GAZA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('712','FAER OER (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('713','GIBILTERRA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('714','MAN (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('715','NORMANNE (ISOLE)=ISOLE DEL CANALE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('716','GEORGIA (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('717','ARMENIA (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('718','AZERBAIGIAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('719','KIRGHIZISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('720','UZBEKISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('721','TAGIKISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('722','TURKEMENISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('723','KAZAKISTAN (fino al 01.01.1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('724','ARABIA MERIDIONALE FEDERAZIONE (fino al 31/12/1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('725','ARABIA MERIDIONALE PROTETTORATO (fino al 31/12/1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('726','COCOS (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('727','RYUKYU ISOLE (fino al 31/12/1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('728','SIKKIM (fino al 31/12/1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('729','VIETNAM DEL SUD (fino al 31/12/1977)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('730','VIETNAM DEL NORD (fino al 31/12/1977)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('732','YEMEN REPUBBLICA DEMOCRATICA POPOLARE (fino al 22/05/1990)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('733','BASUTOLAND-SUD AFRICA BRITANNICO (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('734','BECIUANIA-SUD AFRICA BRITANNICO (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('735','IFNI (fino al 31/12/1984)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('736','LA REUNION (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('737','SAHARA SPAGNOLO (fino al 31/12/1977)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('738','SANT''ELENA (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('739','TERR. FRANCESE DEGLI AFAR E DEGLI ISSA (fino al 31/12/1977)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('740','TANGANICA (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('741','ZANZIBAR (fino al 01/10/1966)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('742','MAYOTTE (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('743','SAHARA MERIDIONALE (fino al 31/12/1984)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('744','SAHARA SETTENTRIONALE (fino al 31/12/1984)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('745','BOPHUTHATSWANA (fino al 01/01/1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('746','TRANSKEI (fino al 01/01/1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('747','VENDA (fino al 01/01/1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('748','CISKEI (fino al 01/01/1994)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('749','NYASALAND (fino al 05/07/1964)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('750','CONGO BELGA (fino al 01/01/1960)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('751','SAINT PIERRE ET MIQUELON (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('752','ANTILLE BRITANNICHE (fino al 31.12.1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('753','ANTILLE OLANDESI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('754','GUADALUPA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('755','MARTINICA','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('756','ANTILLE BRITANNICHE (fino 31/12/1984)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('757','ANGUILLA (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('758','MONTSERRAT','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('759','MALVINE=FALKLAND (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('760','CAROLINE (ISOLE)=STATI FEDERATI DI MICRONESIA (22/12/1990)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('761','CHRISTMAS (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('762','COOK (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('763','GILBERT E ELLICE ISOLE (fino al 3/12/1980)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('764','GUAM (ISOLA)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('765','IRIAN OCCIDENTALE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('766','MACQUARIE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('767','MARCUS ISOLE (fino al 31.12.1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('768','MARIANNE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('769','MIDWAY (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('770','NIUE=SAVAGE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('771','NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('772','NUOVA CALEDONIA (ISOLE E DIPENDENZE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('773','NUOVE EBRIDI CONDOMINIO FRANCO-INGLESE (fino al 31.12.1980)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('774','NUOVA GUINEA (fino al 31.12.1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('775','PAPUASIA (fino al 31.12.1975)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('776','ISOLE CILENE (PASQUA E SALA Y GOMEZ)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('777','PITCAIRN (E DIPENDENZE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('778','POLINESIA FRANCESE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('779','SAMOA AMERICANE (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('780','TOKELAU=ISOLE DELL''UNIONE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('781','WALLIS E FUTUNA (ISOLE)','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('782','DIPENDENZE CANADESI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('783','DIPENDENZE NORVEGESI ARTICHE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('784','DIPENDENZE AUSTRALIANE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('785','DIPENDENZE BRITANNICHE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('786','DIPENDENZE FRANCESI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('787','DIPENDENZE NEOZELANDESI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('788','DIPENDENZE NORVEGESI ANTARTICHE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('789','DIPENDENZE STATUNITENSI','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('790','DIPENDENZE SUDAFRICANE DIPENDENZE SUDAFRICANE','f');
    INSERT INTO public.countries(country,description,existing) VALUES ('200','ITALIA','f');
    */
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('201','BELGIO'::text,'t','201');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('202','DANIMARCA'::text,'t','202');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('203','FRANCIA'::text,'t','203');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('204','GRECIA'::text,'t','204');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('205','IRLANDA'::text,'t','205');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('206','LUSSEMBURGO'::text,'t','206');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('207','PAESI BASSI'::text,'t','207');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('208','PORTOGALLO'::text,'t','208');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('211','SPAGNA'::text,'t','211');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('220','ALBANIA'::text,'t','220');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('221','AUSTRIA'::text,'t','221');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('222','BULGARIA'::text,'t','222');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('223','CECA, REPUBBLICA'::text,'t','223');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('224','SLOVACCHIA'::text,'t','224');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('225','FINLANDIA'::text,'t','225');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('228','MALTA'::text,'t','228');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('229','NORVEGIA'::text,'t','229');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('233','SAN MARINO'::text,'t','233');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('234','SVEZIA'::text,'t','234');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('235','SVIZZERA'::text,'t','235');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('236','TURCHIA'::text,'t','236');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('237','UNGHERIA'::text,'t','237');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('242','MACEDONIA, EX REPUBBLICA JUGOSLAVA DI'::text,'t','242');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('243','BOSNIA ED ERZEGOVINA'::text,'t','243');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('244','CROAZIA'::text,'t','244');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('245','SLOVENIA'::text,'t','245');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('246','ARMENIA'::text,'t','246');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('247','AZERBAIGIAN'::text,'t','247');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('248','GEORGIA'::text,'t','248');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('249','KIRGHIZISTAN'::text,'t','249');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('251','UZBEKISTAN'::text,'t','251');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('253','TAGIKISTAN'::text,'t','253');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('254','TURKMENISTAN'::text,'t','254');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('255','BIELORUSSIA'::text,'t','255');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('256','UCRAINA'::text,'t','256');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('257','KAZAKISTAN'::text,'t','257');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('260','LETTONIA'::text,'t','260');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('261','LITUANIA'::text,'t','261');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('209','REGNO UNITO'::text,'t','209');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('210','GERMANIA'::text,'t','210');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('230','POLONIA'::text,'t','230');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('232','ROMANIA'::text,'t','232');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('250','MOLDAVIA'::text,'t','250');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('252','RUSSA, FEDERAZIONE'::text,'t','252');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('304','MAROCCO'::text,'t','304');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('263','ESTONIA'::text,'t','263');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('317','NIGER'::text,'t','317');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('441','BOLIVIA'::text,'t','441');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('442','BRASILE'::text,'t','442');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('529','SRI LANKA (EX CEYLON)'::text,'t','529');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('530','INDIA'::text,'t','530');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('266','ISLANDA'::text,'t','266');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('270','ANDORRA'::text,'t','270');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('271','CITTA'' DEL VATICANO'::text,'t','271');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('272','LIECHTENSTEIN'::text,'t','272');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('273','MONACO'::text,'t','273');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('301','ALGERIA'::text,'t','301');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('302','EGITTO'::text,'t','302');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('303','LIBIA'::text,'t','303');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('305','SUDAN'::text,'t','305');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('306','TUNISIA'::text,'t','306');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('307','GUINEA BISSAU'::text,'t','307');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('309','SIERRA LEONE'::text,'t','309');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('310','BURKINA FASO (EX ALTO VOLTA)'::text,'t','310');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('311','CIAD'::text,'t','311');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('312','COSTA D''AVORIO'::text,'t','312');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('313','GHANA'::text,'t','313');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('314','GUINEA'::text,'t','314');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('315','MALI'::text,'t','315');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('316','NIGERIA'::text,'t','316');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('318','CAPO VERDE'::text,'t','318');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('319','SENEGAL'::text,'t','319');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('320','REPUBBLICA SUDAFRICANA'::text,'t','320');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('321','LIBERIA'::text,'t','321');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('322','SWAZILAND'::text,'t','322');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('323','BURUNDI'::text,'t','323');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('328','SEICELLE'::text,'t','328');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('329','MAURITIUS'::text,'t','329');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('330','ANGOLA'::text,'t','330');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('331','CAMERUN'::text,'t','331');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('332','ETIOPIA'::text,'t','332');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('333','COMORE'::text,'t','333');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('334','MADAGASCAR'::text,'t','334');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('335','MALAWI'::text,'t','335');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('336','KENYA'::text,'t','336');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('337','MOZAMBICO'::text,'t','337');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('338','LESOTHO'::text,'t','338');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('339','RUANDA'::text,'t','339');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('340','SOMALIA'::text,'t','340');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('341','TANZANIA'::text,'t','341');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('342','UGANDA'::text,'t','342');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('343','CONGO, REPUBBLICA DEMOCRATICA DEL (EX ZAIRE)'::text,'t','343');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('344','ZAMBIA'::text,'t','344');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('345','ZIMBABWE (EX RHODESIA)'::text,'t','345');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('347','MAURITANIA'::text,'t','347');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('348','GAMBIA'::text,'t','348');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('349','BENIN (EX DAHOMEY)'::text,'t','349');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('350','TOGO'::text,'t','350');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('351','BOTSWANA'::text,'t','351');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('352','CENTRAFRICANA REPUBBLICA'::text,'t','352');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('353','CONGO, REPUBBLICA POPOLARE'::text,'t','353');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('354','ERITREA'::text,'t','354');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('355','SAO TOME'' E PRINCIPE'::text,'t','355');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('356','GIBUTI'::text,'t','356');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('357','NAMIBIA'::text,'t','357');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('358','GUINEA EQUATORIALE'::text,'t','358');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('359','GABON'::text,'t','359');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('401','CANADA'::text,'t','401');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('402','STATI UNITI D''AMERICA'::text,'t','402');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('403','REPUBBLICA DELLA GUAYANA'::text,'t','403');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('404','SURINAME'::text,'t','404');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('405','BARBADOS'::text,'t','405');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('410','COSTA RICA'::text,'t','410');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('411','CUBA'::text,'t','411');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('412','EL SALVADOR'::text,'t','412');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('413','GIAMAICA'::text,'t','413');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('414','GUATEMALA'::text,'t','414');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('415','HAITI'::text,'t','415');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('416','HONDURAS'::text,'t','416');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('417','MESSICO'::text,'t','417');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('418','NICARAGUA'::text,'t','418');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('419','PANAMA'::text,'t','419');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('420','REPUBBLICA DOMINICANA'::text,'t','420');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('428','BELIZE'::text,'t','428');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('440','ARGENTINA'::text,'t','440');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('443','CILE'::text,'t','443');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('444','COLOMBIA'::text,'t','444');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('445','ECUADOR'::text,'t','445');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('446','PARAGUAY'::text,'t','446');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('447','PERU'::text,'t','447');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('449','URUGUAY'::text,'t','449');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('450','VENEZUELA'::text,'t','450');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('460','ANTIGUA E BARBUDA'::text,'t','460');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('461','BAHAMA'::text,'t','461');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('462','DOMINICA'::text,'t','462');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('463','GRENADA'::text,'t','463');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('464','SAINT VINCENT E GRENADINE'::text,'t','464');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('465','SAINT KITTS E NEVIS'::text,'t','465');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('466','SAINT LUCIA'::text,'t','466');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('498','TRINIDAD E TOBAGO'::text,'t','498');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('500','PALESTINA (TERRITORI DELL''AUTONOMIA PALESTINESE)'::text,'t','500');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('501','ARABIA SAUDITA'::text,'t','501');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('502','CIPRO'::text,'t','502');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('503','GIORDANIA'::text,'t','503');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('504','IRAN'::text,'t','504');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('505','IRAQ'::text,'t','505');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('506','ISRAELE'::text,'t','506');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('507','LIBANO'::text,'t','507');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('508','SIRIA'::text,'t','508');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('509','YEMEN'::text,'t','509');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('510','AFGHANISTAN'::text,'t','510');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('519','CAMBOGIA'::text,'t','519');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('520','BANGLADESH'::text,'t','520');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('521','BHUTAN'::text,'t','521');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('522','MYANMAR (EX BIRMANIA)'::text,'t','522');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('523','LAOS'::text,'t','523');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('524','CINA REPUBBLICA POPOLARE'::text,'t','524');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('525','COREA, REPUBBLICA POPOLARE DEMOCRATICA (COREA DEL NORD)'::text,'t','525');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('526','COREA, REPUBBLICA (COREA DEL SUD)'::text,'t','526');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('527','FILIPPINE'::text,'t','527');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('528','GIAPPONE GIAPPONE'::text,'t','528');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('531','BRUNEI'::text,'t','531');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('532','INDONESIA'::text,'t','532');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('533','NEPAL'::text,'t','533');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('534','PAKISTAN'::text,'t','534');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('535','MALDIVE'::text,'t','535');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('536','THAILANDIA'::text,'t','536');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('537','TAIWAN (EX FORMOSA)'::text,'t','537');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('538','VIETNAM'::text,'t','538');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('551','KUWAIT'::text,'t','551');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('552','MONGOLIA REP. POPOLARE'::text,'t','552');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('553','SINGAPORE'::text,'t','553');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('560','BAHEREIN'::text,'t','560');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('561','EMIRATI ARABI UNITI'::text,'t','561');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('562','OMAN'::text,'t','562');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('563','QATAR'::text,'t','563');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('600','MARSHALL, ISOLE'::text,'t','600');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('601','AUSTRALIA'::text,'t','601');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('602','NUOVA ZELANDA'::text,'t','602');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('603','FIGI O VITI'::text,'t','603');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('604','KIRIBATI'::text,'t','604');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('605','PAPUA NUOVA GUINEA'::text,'t','605');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('606','SALOMONE, ISOLE'::text,'t','606');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('607','SAMOA'::text,'t','607');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('608','TONGA'::text,'t','608');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('609','TUVALU'::text,'t','609');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('610','MICRONESIA'::text,'t','610');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('611','NAURU'::text,'t','611');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('612','PALAU'::text,'t','612');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('613','VANUATU'::text,'t','613');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('700','APOLIDI'::text,'t','700');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('701','MONTENEGRO ONTENEGRO'::text,'t','701');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('702','SERBIA,REPUBBLICA DI'::text,'t','702');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('709','KOSOVO'::text,'t','709');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('731','MALAYSIA'::text,'t','731');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('227','IUGOSLAVIA (fino al 04/02/2003)'::text,'f','227');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('231','GROENLANDIA'::text,'f','231');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('238','URSS (fino al 31/03/1992)'::text,'f','238');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('241','SERBIA E MONTENEGRO (fino al 02/06/2006)'::text,'f','241');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('468','ISOLE VERGINI USA'::text,'f','468');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('470','ISOLE VERGINI B. E MONTSERRAT'::text,'f','470');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('471','ISOLE CAYMAN'::text,'f','471');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('472','ISOLE TURKS E CAICOS'::text,'f','472');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('474','PUERTO RICO'::text,'f','474');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('477','BERMUDE'::text,'f','477');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('515','MALESIA (fino al 01/10/1966)'::text,'f','515');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('516','HONG KONG (fino al01/07/1997)'::text,'f','516');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('518','MACAO'::text,'f','518');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('704','TIMOR ORIENTALE (fino al 31/12/1978)'::text,'f','704');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('705','CECOSLOVACCHIA (fino al 01/01/1993)'::text,'f','705');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('706','DIPENDENZE SOVIETICHE'::text,'f','706');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('707','GERMANIA REPUBBLICA DEMOCRATICA (fino al 03/10/1990)'::text,'f','707');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('708','GUAYANA FRANCESE'::text,'f','708');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('711','TERRITORIO DI GAZA'::text,'f','711');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('712','FAER OER (ISOLE)'::text,'f','712');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('713','GIBILTERRA'::text,'f','713');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('714','MAN (ISOLA)'::text,'f','714');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('715','NORMANNE (ISOLE)=ISOLE DEL CANALE'::text,'f','715');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('716','GEORGIA (fino al 01.01.1994)'::text,'f','716');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('717','ARMENIA (fino al 01.01.1994)'::text,'f','717');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('718','AZERBAIGIAN (fino al 01.01.1994)'::text,'f','718');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('719','KIRGHIZISTAN (fino al 01.01.1994)'::text,'f','719');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('720','UZBEKISTAN (fino al 01.01.1994)'::text,'f','720');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('721','TAGIKISTAN (fino al 01.01.1994)'::text,'f','721');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('722','TURKEMENISTAN (fino al 01.01.1994)'::text,'f','722');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('723','KAZAKISTAN (fino al 01.01.1994)'::text,'f','723');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('724','ARABIA MERIDIONALE FEDERAZIONE (fino al 31/12/1975)'::text,'f','724');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('725','ARABIA MERIDIONALE PROTETTORATO (fino al 31/12/1975)'::text,'f','725');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('726','COCOS (ISOLE)'::text,'f','726');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('727','RYUKYU ISOLE (fino al 31/12/1975)'::text,'f','727');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('728','SIKKIM (fino al 31/12/1975)'::text,'f','728');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('729','VIETNAM DEL SUD (fino al 31/12/1977)'::text,'f','729');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('730','VIETNAM DEL NORD (fino al 31/12/1977)'::text,'f','730');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('732','YEMEN REPUBBLICA DEMOCRATICA POPOLARE (fino al 22/05/1990)'::text,'f','732');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('733','BASUTOLAND-SUD AFRICA BRITANNICO (fino al 01/10/1966)'::text,'f','733');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('734','BECIUANIA-SUD AFRICA BRITANNICO (fino al 01/10/1966)'::text,'f','734');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('735','IFNI (fino al 31/12/1984)'::text,'f','735');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('736','LA REUNION (ISOLA)'::text,'f','736');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('737','SAHARA SPAGNOLO (fino al 31/12/1977)'::text,'f','737');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('738','SANT''ELENA (ISOLA)'::text,'f','738');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('739','TERR. FRANCESE DEGLI AFAR E DEGLI ISSA (fino al 31/12/1977)'::text,'f','739');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('740','TANGANICA (fino al 01/10/1966)'::text,'f','740');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('741','ZANZIBAR (fino al 01/10/1966)'::text,'f','741');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('742','MAYOTTE (ISOLA)'::text,'f','742');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('743','SAHARA MERIDIONALE (fino al 31/12/1984)'::text,'f','743');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('744','SAHARA SETTENTRIONALE (fino al 31/12/1984)'::text,'f','744');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('745','BOPHUTHATSWANA (fino al 01/01/1994)'::text,'f','745');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('746','TRANSKEI (fino al 01/01/1994)'::text,'f','746');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('747','VENDA (fino al 01/01/1994)'::text,'f','747');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('748','CISKEI (fino al 01/01/1994)'::text,'f','748');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('749','NYASALAND (fino al 05/07/1964)'::text,'f','749');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('750','CONGO BELGA (fino al 01/01/1960)'::text,'f','750');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('751','SAINT PIERRE ET MIQUELON (ISOLE)'::text,'f','751');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('752','ANTILLE BRITANNICHE (fino al 31.12.1975)'::text,'f','752');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('753','ANTILLE OLANDESI'::text,'f','753');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('754','GUADALUPA'::text,'f','754');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('755','MARTINICA'::text,'f','755');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('756','ANTILLE BRITANNICHE (fino 31/12/1984)'::text,'f','756');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('757','ANGUILLA (ISOLA)'::text,'f','757');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('758','MONTSERRAT'::text,'f','758');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('759','MALVINE=FALKLAND (ISOLE)'::text,'f','759');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('760','CAROLINE (ISOLE)=STATI FEDERATI DI MICRONESIA (22/12/1990)'::text,'f','760');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('761','CHRISTMAS (ISOLA)'::text,'f','761');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('762','COOK (ISOLE)'::text,'f','762');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('763','GILBERT E ELLICE ISOLE (fino al 3/12/1980)'::text,'f','763');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('764','GUAM (ISOLA)'::text,'f','764');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('765','IRIAN OCCIDENTALE'::text,'f','765');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('766','MACQUARIE (ISOLE)'::text,'f','766');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('767','MARCUS ISOLE (fino al 31.12.1975)'::text,'f','767');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('768','MARIANNE (ISOLE)'::text,'f','768');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('769','MIDWAY (ISOLE)'::text,'f','769');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('770','NIUE=SAVAGE (ISOLE)'::text,'f','770');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('771','NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)'::text,'f','771');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('772','NUOVA CALEDONIA (ISOLE E DIPENDENZE)'::text,'f','772');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('773','NUOVE EBRIDI CONDOMINIO FRANCO-INGLESE (fino al 31.12.1980)'::text,'f','773');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('774','NUOVA GUINEA (fino al 31.12.1975)'::text,'f','774');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('775','PAPUASIA (fino al 31.12.1975)'::text,'f','775');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('776','ISOLE CILENE (PASQUA E SALA Y GOMEZ)'::text,'f','776');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('777','PITCAIRN (E DIPENDENZE)'::text,'f','777');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('778','POLINESIA FRANCESE (ISOLE)'::text,'f','778');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('779','SAMOA AMERICANE (ISOLE)'::text,'f','779');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('780','TOKELAU=ISOLE DELL''UNIONE'::text,'f','780');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('781','WALLIS E FUTUNA (ISOLE)'::text,'f','781');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('782','DIPENDENZE CANADESI'::text,'f','782');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('783','DIPENDENZE NORVEGESI ARTICHE'::text,'f','783');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('784','DIPENDENZE AUSTRALIANE'::text,'f','784');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('785','DIPENDENZE BRITANNICHE'::text,'f','785');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('786','DIPENDENZE FRANCESI'::text,'f','786');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('787','DIPENDENZE NEOZELANDESI'::text,'f','787');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('788','DIPENDENZE NORVEGESI ANTARTICHE'::text,'f','788');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('789','DIPENDENZE STATUNITENSI'::text,'f','789');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('790','DIPENDENZE SUDAFRICANE DIPENDENZE SUDAFRICANE'::text,'f','790');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('200','ITALIA'::text,'f','200');


    _results = _results || assert.pass(full_function_name, test_name);

    EXCEPTION
       WHEN OTHERS THEN 
         GET STACKED DIAGNOSTICS error.returned_sqlstate = RETURNED_SQLSTATE, error.message_text = MESSAGE_TEXT, error.schema_name = SCHEMA_NAME, error.table_name = TABLE_NAME, error.column_name = COLUMN_NAME, error.constraint_name = CONSTRAINT_NAME, error.pg_exception_context = PG_EXCEPTION_CONTEXT, error.pg_exception_detail = PG_EXCEPTION_DETAIL, error.pg_exception_hint = PG_EXCEPTION_HINT, error.pg_datatype_name = PG_DATATYPE_NAME;
         _results = _results || assert.fail(full_function_name, test_name, 'INSERT public.countries FAILED'::text, error);   
       RETURN; 
  END;
  RETURN; 
END
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION unit_tests_public.countries(boolean)
  OWNER TO postgres;
