format
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('201','BELGIO (test)','t','201');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('202','DANIMARCA (test)','t','202');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('203','FRANCIA (test)','t','203');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('204','GRECIA (test)','t','204');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('205','IRLANDA (test)','t','205');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('206','LUSSEMBURGO (test)','t','206');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('207','PAESI BASSI (test)','t','207');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('208','PORTOGALLO (test)','t','208');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('211','SPAGNA (test)','t','211');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('220','ALBANIA (test)','t','220');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('221','AUSTRIA (test)','t','221');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('222','BULGARIA (test)','t','222');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('223','CECA, REPUBBLICA (test)','t','223');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('224','SLOVACCHIA (test)','t','224');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('225','FINLANDIA (test)','t','225');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('228','MALTA (test)','t','228');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('229','NORVEGIA (test)','t','229');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('233','SAN MARINO (test)','t','233');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('234','SVEZIA (test)','t','234');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('235','SVIZZERA (test)','t','235');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('236','TURCHIA (test)','t','236');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('237','UNGHERIA (test)','t','237');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('242','MACEDONIA, EX REPUBBLICA JUGOSLAVA DI (test)','t','242');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('243','BOSNIA ED ERZEGOVINA (test)','t','243');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('244','CROAZIA (test)','t','244');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('245','SLOVENIA (test)','t','245');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('246','ARMENIA (test)','t','246');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('247','AZERBAIGIAN (test)','t','247');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('248','GEORGIA (test)','t','248');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('249','KIRGHIZISTAN (test)','t','249');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('251','UZBEKISTAN (test)','t','251');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('253','TAGIKISTAN (test)','t','253');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('254','TURKMENISTAN (test)','t','254');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('255','BIELORUSSIA (test)','t','255');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('256','UCRAINA (test)','t','256');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('257','KAZAKISTAN (test)','t','257');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('260','LETTONIA (test)','t','260');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('261','LITUANIA (test)','t','261');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('209','REGNO UNITO (test)','t','209');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('210','GERMANIA (test)','t','210');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('230','POLONIA (test)','t','230');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('232','ROMANIA (test)','t','232');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('250','MOLDAVIA (test)','t','250');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('252','RUSSA, FEDERAZIONE (test)','t','252');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('304','MAROCCO (test)','t','304');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('263','ESTONIA (test)','t','263');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('317','NIGER (test)','t','317');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('441','BOLIVIA (test)','t','441');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('442','BRASILE (test)','t','442');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('529','SRI LANKA (EX CEYLON) (test)','t','529');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('530','INDIA (test)','t','530');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('266','ISLANDA (test)','t','266');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('270','ANDORRA (test)','t','270');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('271','CITTA'' DEL VATICANO (test)','t','271');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('272','LIECHTENSTEIN (test)','t','272');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('273','MONACO (test)','t','273');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('301','ALGERIA (test)','t','301');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('302','EGITTO (test)','t','302');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('303','LIBIA (test)','t','303');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('305','SUDAN (test)','t','305');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('306','TUNISIA (test)','t','306');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('307','GUINEA BISSAU (test)','t','307');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('309','SIERRA LEONE (test)','t','309');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('310','BURKINA FASO (EX ALTO VOLTA) (test)','t','310');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('311','CIAD (test)','t','311');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('312','COSTA D''AVORIO (test)','t','312');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('313','GHANA (test)','t','313');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('314','GUINEA (test)','t','314');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('315','MALI (test)','t','315');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('316','NIGERIA (test)','t','316');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('318','CAPO VERDE (test)','t','318');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('319','SENEGAL (test)','t','319');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('320','REPUBBLICA SUDAFRICANA (test)','t','320');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('321','LIBERIA (test)','t','321');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('322','SWAZILAND (test)','t','322');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('323','BURUNDI (test)','t','323');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('328','SEICELLE (test)','t','328');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('329','MAURITIUS (test)','t','329');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('330','ANGOLA (test)','t','330');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('331','CAMERUN (test)','t','331');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('332','ETIOPIA (test)','t','332');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('333','COMORE (test)','t','333');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('334','MADAGASCAR (test)','t','334');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('335','MALAWI (test)','t','335');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('336','KENYA (test)','t','336');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('337','MOZAMBICO (test)','t','337');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('338','LESOTHO (test)','t','338');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('339','RUANDA (test)','t','339');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('340','SOMALIA (test)','t','340');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('341','TANZANIA (test)','t','341');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('342','UGANDA (test)','t','342');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('343','CONGO, REPUBBLICA DEMOCRATICA DEL (EX ZAIRE) (test)','t','343');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('344','ZAMBIA (test)','t','344');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('345','ZIMBABWE (EX RHODESIA) (test)','t','345');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('347','MAURITANIA (test)','t','347');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('348','GAMBIA (test)','t','348');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('349','BENIN (EX DAHOMEY) (test)','t','349');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('350','TOGO (test)','t','350');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('351','BOTSWANA (test)','t','351');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('352','CENTRAFRICANA REPUBBLICA (test)','t','352');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('353','CONGO, REPUBBLICA POPOLARE (test)','t','353');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('354','ERITREA (test)','t','354');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('355','SAO TOME'' E PRINCIPE (test)','t','355');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('356','GIBUTI (test)','t','356');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('357','NAMIBIA (test)','t','357');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('358','GUINEA EQUATORIALE (test)','t','358');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('359','GABON (test)','t','359');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('401','CANADA (test)','t','401');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('402','STATI UNITI D''AMERICA (test)','t','402');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('403','REPUBBLICA DELLA GUAYANA (test)','t','403');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('404','SURINAME (test)','t','404');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('405','BARBADOS (test)','t','405');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('410','COSTA RICA (test)','t','410');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('411','CUBA (test)','t','411');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('412','EL SALVADOR (test)','t','412');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('413','GIAMAICA (test)','t','413');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('414','GUATEMALA (test)','t','414');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('415','HAITI (test)','t','415');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('416','HONDURAS (test)','t','416');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('417','MESSICO (test)','t','417');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('418','NICARAGUA (test)','t','418');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('419','PANAMA (test)','t','419');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('420','REPUBBLICA DOMINICANA (test)','t','420');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('428','BELIZE (test)','t','428');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('440','ARGENTINA (test)','t','440');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('443','CILE (test)','t','443');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('444','COLOMBIA (test)','t','444');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('445','ECUADOR (test)','t','445');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('446','PARAGUAY (test)','t','446');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('447','PERU (test)','t','447');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('449','URUGUAY (test)','t','449');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('450','VENEZUELA (test)','t','450');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('460','ANTIGUA E BARBUDA (test)','t','460');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('461','BAHAMA (test)','t','461');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('462','DOMINICA (test)','t','462');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('463','GRENADA (test)','t','463');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('464','SAINT VINCENT E GRENADINE (test)','t','464');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('465','SAINT KITTS E NEVIS (test)','t','465');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('466','SAINT LUCIA (test)','t','466');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('498','TRINIDAD E TOBAGO (test)','t','498');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('500','PALESTINA (TERRITORI DELL''AUTONOMIA PALESTINESE) (test)','t','500');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('501','ARABIA SAUDITA (test)','t','501');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('502','CIPRO (test)','t','502');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('503','GIORDANIA (test)','t','503');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('504','IRAN (test)','t','504');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('505','IRAQ (test)','t','505');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('506','ISRAELE (test)','t','506');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('507','LIBANO (test)','t','507');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('508','SIRIA (test)','t','508');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('509','YEMEN (test)','t','509');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('510','AFGHANISTAN (test)','t','510');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('519','CAMBOGIA (test)','t','519');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('520','BANGLADESH (test)','t','520');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('521','BHUTAN (test)','t','521');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('522','MYANMAR (EX BIRMANIA) (test)','t','522');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('523','LAOS (test)','t','523');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('524','CINA REPUBBLICA POPOLARE (test)','t','524');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('525','COREA, REPUBBLICA POPOLARE DEMOCRATICA (COREA DEL NORD) (test)','t','525');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('526','COREA, REPUBBLICA (COREA DEL SUD) (test)','t','526');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('527','FILIPPINE (test)','t','527');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('528','GIAPPONE GIAPPONE (test)','t','528');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('531','BRUNEI (test)','t','531');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('532','INDONESIA (test)','t','532');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('533','NEPAL (test)','t','533');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('534','PAKISTAN (test)','t','534');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('535','MALDIVE (test)','t','535');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('536','THAILANDIA (test)','t','536');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('537','TAIWAN (EX FORMOSA) (test)','t','537');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('538','VIETNAM (test)','t','538');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('551','KUWAIT (test)','t','551');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('552','MONGOLIA REP. POPOLARE (test)','t','552');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('553','SINGAPORE (test)','t','553');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('560','BAHEREIN (test)','t','560');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('561','EMIRATI ARABI UNITI (test)','t','561');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('562','OMAN (test)','t','562');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('563','QATAR (test)','t','563');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('600','MARSHALL, ISOLE (test)','t','600');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('601','AUSTRALIA (test)','t','601');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('602','NUOVA ZELANDA (test)','t','602');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('603','FIGI O VITI (test)','t','603');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('604','KIRIBATI (test)','t','604');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('605','PAPUA NUOVA GUINEA (test)','t','605');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('606','SALOMONE, ISOLE (test)','t','606');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('607','SAMOA (test)','t','607');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('608','TONGA (test)','t','608');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('609','TUVALU (test)','t','609');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('610','MICRONESIA (test)','t','610');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('611','NAURU (test)','t','611');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('612','PALAU (test)','t','612');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('613','VANUATU (test)','t','613');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('700','APOLIDI (test)','t','700');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('701','MONTENEGRO ONTENEGRO (test)','t','701');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('702','SERBIA,REPUBBLICA DI (test)','t','702');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('709','KOSOVO (test)','t','709');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('731','MALAYSIA (test)','t','731');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('227','IUGOSLAVIA (fino al 04/02/2003) (test)','f','227');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('231','GROENLANDIA (test)','f','231');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('238','URSS (fino al 31/03/1992) (test)','f','238');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('241','SERBIA E MONTENEGRO (fino al 02/06/2006) (test)','f','241');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('468','ISOLE VERGINI USA (test)','f','468');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('470','ISOLE VERGINI B. E MONTSERRAT (test)','f','470');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('471','ISOLE CAYMAN (test)','f','471');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('472','ISOLE TURKS E CAICOS (test)','f','472');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('474','PUERTO RICO (test)','f','474');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('477','BERMUDE (test)','f','477');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('515','MALESIA (fino al 01/10/1966) (test)','f','515');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('516','HONG KONG (fino al01/07/1997) (test)','f','516');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('518','MACAO (test)','f','518');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('704','TIMOR ORIENTALE (fino al 31/12/1978) (test)','f','704');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('705','CECOSLOVACCHIA (fino al 01/01/1993) (test)','f','705');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('706','DIPENDENZE SOVIETICHE (test)','f','706');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('707','GERMANIA REPUBBLICA DEMOCRATICA (fino al 03/10/1990) (test)','f','707');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('708','GUAYANA FRANCESE (test)','f','708');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('711','TERRITORIO DI GAZA (test)','f','711');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('712','FAER OER (ISOLE) (test)','f','712');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('713','GIBILTERRA (test)','f','713');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('714','MAN (ISOLA) (test)','f','714');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('715','NORMANNE (ISOLE)=ISOLE DEL CANALE (test)','f','715');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('716','GEORGIA (fino al 01.01.1994) (test)','f','716');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('717','ARMENIA (fino al 01.01.1994) (test)','f','717');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('718','AZERBAIGIAN (fino al 01.01.1994) (test)','f','718');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('719','KIRGHIZISTAN (fino al 01.01.1994) (test)','f','719');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('720','UZBEKISTAN (fino al 01.01.1994) (test)','f','720');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('721','TAGIKISTAN (fino al 01.01.1994) (test)','f','721');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('722','TURKEMENISTAN (fino al 01.01.1994) (test)','f','722');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('723','KAZAKISTAN (fino al 01.01.1994) (test)','f','723');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('724','ARABIA MERIDIONALE FEDERAZIONE (fino al 31/12/1975) (test)','f','724');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('725','ARABIA MERIDIONALE PROTETTORATO (fino al 31/12/1975) (test)','f','725');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('726','COCOS (ISOLE) (test)','f','726');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('727','RYUKYU ISOLE (fino al 31/12/1975) (test)','f','727');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('728','SIKKIM (fino al 31/12/1975) (test)','f','728');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('729','VIETNAM DEL SUD (fino al 31/12/1977) (test)','f','729');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('730','VIETNAM DEL NORD (fino al 31/12/1977) (test)','f','730');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('732','YEMEN REPUBBLICA DEMOCRATICA POPOLARE (fino al 22/05/1990) (test)','f','732');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('733','BASUTOLAND-SUD AFRICA BRITANNICO (fino al 01/10/1966) (test)','f','733');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('734','BECIUANIA-SUD AFRICA BRITANNICO (fino al 01/10/1966) (test)','f','734');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('735','IFNI (fino al 31/12/1984) (test)','f','735');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('736','LA REUNION (ISOLA) (test)','f','736');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('737','SAHARA SPAGNOLO (fino al 31/12/1977) (test)','f','737');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('738','SANT''ELENA (ISOLA) (test)','f','738');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('739','TERR. FRANCESE DEGLI AFAR E DEGLI ISSA (fino al 31/12/1977) (test)','f','739');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('740','TANGANICA (fino al 01/10/1966) (test)','f','740');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('741','ZANZIBAR (fino al 01/10/1966) (test)','f','741');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('742','MAYOTTE (ISOLA) (test)','f','742');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('743','SAHARA MERIDIONALE (fino al 31/12/1984) (test)','f','743');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('744','SAHARA SETTENTRIONALE (fino al 31/12/1984) (test)','f','744');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('745','BOPHUTHATSWANA (fino al 01/01/1994) (test)','f','745');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('746','TRANSKEI (fino al 01/01/1994) (test)','f','746');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('747','VENDA (fino al 01/01/1994) (test)','f','747');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('748','CISKEI (fino al 01/01/1994) (test)','f','748');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('749','NYASALAND (fino al 05/07/1964) (test)','f','749');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('750','CONGO BELGA (fino al 01/01/1960) (test)','f','750');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('751','SAINT PIERRE ET MIQUELON (ISOLE) (test)','f','751');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('752','ANTILLE BRITANNICHE (fino al 31.12.1975) (test)','f','752');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('753','ANTILLE OLANDESI (test)','f','753');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('754','GUADALUPA (test)','f','754');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('755','MARTINICA (test)','f','755');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('756','ANTILLE BRITANNICHE (fino 31/12/1984) (test)','f','756');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('757','ANGUILLA (ISOLA) (test)','f','757');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('758','MONTSERRAT (test)','f','758');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('759','MALVINE=FALKLAND (ISOLE) (test)','f','759');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('760','CAROLINE (ISOLE)=STATI FEDERATI DI MICRONESIA (22/12/1990) (test)','f','760');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('761','CHRISTMAS (ISOLA) (test)','f','761');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('762','COOK (ISOLE) (test)','f','762');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('763','GILBERT E ELLICE ISOLE (fino al 3/12/1980) (test)','f','763');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('764','GUAM (ISOLA) (test)','f','764');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('765','IRIAN OCCIDENTALE (test)','f','765');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('766','MACQUARIE (ISOLE) (test)','f','766');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('767','MARCUS ISOLE (fino al 31.12.1975) (test)','f','767');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('768','MARIANNE (ISOLE) (test)','f','768');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('769','MIDWAY (ISOLE) (test)','f','769');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('770','NIUE=SAVAGE (ISOLE) (test)','f','770');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('771','NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI) (test)','f','771');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('772','NUOVA CALEDONIA (ISOLE E DIPENDENZE) (test)','f','772');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('773','NUOVE EBRIDI CONDOMINIO FRANCO-INGLESE (fino al 31.12.1980) (test)','f','773');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('774','NUOVA GUINEA (fino al 31.12.1975) (test)','f','774');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('775','PAPUASIA (fino al 31.12.1975) (test)','f','775');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('776','ISOLE CILENE (PASQUA E SALA Y GOMEZ) (test)','f','776');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('777','PITCAIRN (E DIPENDENZE) (test)','f','777');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('778','POLINESIA FRANCESE (ISOLE) (test)','f','778');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('779','SAMOA AMERICANE (ISOLE) (test)','f','779');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('780','TOKELAU=ISOLE DELL''UNIONE (test)','f','780');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('781','WALLIS E FUTUNA (ISOLE) (test)','f','781');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('782','DIPENDENZE CANADESI (test)','f','782');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('783','DIPENDENZE NORVEGESI ARTICHE (test)','f','783');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('784','DIPENDENZE AUSTRALIANE (test)','f','784');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('785','DIPENDENZE BRITANNICHE (test)','f','785');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('786','DIPENDENZE FRANCESI (test)','f','786');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('787','DIPENDENZE NEOZELANDESI (test)','f','787');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('788','DIPENDENZE NORVEGESI ANTARTICHE (test)','f','788');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('789','DIPENDENZE STATUNITENSI (test)','f','789');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('790','DIPENDENZE SUDAFRICANE DIPENDENZE SUDAFRICANE (test)','f','790');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('200','ITALIA (test)','f','200');
