format
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('201','BELGIO'_text,'t','201');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('202','DANIMARCA'_text,'t','202');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('203','FRANCIA'_text,'t','203');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('204','GRECIA'_text,'t','204');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('205','IRLANDA'_text,'t','205');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('206','LUSSEMBURGO'_text,'t','206');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('207','PAESI BASSI'_text,'t','207');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('208','PORTOGALLO'_text,'t','208');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('211','SPAGNA'_text,'t','211');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('220','ALBANIA'_text,'t','220');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('221','AUSTRIA'_text,'t','221');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('222','BULGARIA'_text,'t','222');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('223','CECA, REPUBBLICA'_text,'t','223');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('224','SLOVACCHIA'_text,'t','224');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('225','FINLANDIA'_text,'t','225');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('228','MALTA'_text,'t','228');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('229','NORVEGIA'_text,'t','229');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('233','SAN MARINO'_text,'t','233');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('234','SVEZIA'_text,'t','234');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('235','SVIZZERA'_text,'t','235');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('236','TURCHIA'_text,'t','236');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('237','UNGHERIA'_text,'t','237');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('242','MACEDONIA, EX REPUBBLICA JUGOSLAVA DI'_text,'t','242');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('243','BOSNIA ED ERZEGOVINA'_text,'t','243');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('244','CROAZIA'_text,'t','244');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('245','SLOVENIA'_text,'t','245');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('246','ARMENIA'_text,'t','246');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('247','AZERBAIGIAN'_text,'t','247');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('248','GEORGIA'_text,'t','248');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('249','KIRGHIZISTAN'_text,'t','249');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('251','UZBEKISTAN'_text,'t','251');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('253','TAGIKISTAN'_text,'t','253');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('254','TURKMENISTAN'_text,'t','254');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('255','BIELORUSSIA'_text,'t','255');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('256','UCRAINA'_text,'t','256');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('257','KAZAKISTAN'_text,'t','257');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('260','LETTONIA'_text,'t','260');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('261','LITUANIA'_text,'t','261');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('209','REGNO UNITO'_text,'t','209');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('210','GERMANIA'_text,'t','210');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('230','POLONIA'_text,'t','230');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('232','ROMANIA'_text,'t','232');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('250','MOLDAVIA'_text,'t','250');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('252','RUSSA, FEDERAZIONE'_text,'t','252');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('304','MAROCCO'_text,'t','304');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('263','ESTONIA'_text,'t','263');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('317','NIGER'_text,'t','317');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('441','BOLIVIA'_text,'t','441');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('442','BRASILE'_text,'t','442');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('529','SRI LANKA (EX CEYLON)'_text,'t','529');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('530','INDIA'_text,'t','530');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('266','ISLANDA'_text,'t','266');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('270','ANDORRA'_text,'t','270');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('271','CITTA'' DEL VATICANO'_text,'t','271');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('272','LIECHTENSTEIN'_text,'t','272');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('273','MONACO'_text,'t','273');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('301','ALGERIA'_text,'t','301');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('302','EGITTO'_text,'t','302');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('303','LIBIA'_text,'t','303');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('305','SUDAN'_text,'t','305');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('306','TUNISIA'_text,'t','306');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('307','GUINEA BISSAU'_text,'t','307');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('309','SIERRA LEONE'_text,'t','309');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('310','BURKINA FASO (EX ALTO VOLTA)'_text,'t','310');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('311','CIAD'_text,'t','311');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('312','COSTA D''AVORIO'_text,'t','312');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('313','GHANA'_text,'t','313');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('314','GUINEA'_text,'t','314');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('315','MALI'_text,'t','315');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('316','NIGERIA'_text,'t','316');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('318','CAPO VERDE'_text,'t','318');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('319','SENEGAL'_text,'t','319');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('320','REPUBBLICA SUDAFRICANA'_text,'t','320');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('321','LIBERIA'_text,'t','321');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('322','SWAZILAND'_text,'t','322');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('323','BURUNDI'_text,'t','323');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('328','SEICELLE'_text,'t','328');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('329','MAURITIUS'_text,'t','329');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('330','ANGOLA'_text,'t','330');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('331','CAMERUN'_text,'t','331');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('332','ETIOPIA'_text,'t','332');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('333','COMORE'_text,'t','333');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('334','MADAGASCAR'_text,'t','334');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('335','MALAWI'_text,'t','335');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('336','KENYA'_text,'t','336');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('337','MOZAMBICO'_text,'t','337');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('338','LESOTHO'_text,'t','338');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('339','RUANDA'_text,'t','339');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('340','SOMALIA'_text,'t','340');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('341','TANZANIA'_text,'t','341');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('342','UGANDA'_text,'t','342');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('343','CONGO, REPUBBLICA DEMOCRATICA DEL (EX ZAIRE)'_text,'t','343');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('344','ZAMBIA'_text,'t','344');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('345','ZIMBABWE (EX RHODESIA)'_text,'t','345');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('347','MAURITANIA'_text,'t','347');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('348','GAMBIA'_text,'t','348');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('349','BENIN (EX DAHOMEY)'_text,'t','349');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('350','TOGO'_text,'t','350');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('351','BOTSWANA'_text,'t','351');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('352','CENTRAFRICANA REPUBBLICA'_text,'t','352');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('353','CONGO, REPUBBLICA POPOLARE'_text,'t','353');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('354','ERITREA'_text,'t','354');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('355','SAO TOME'' E PRINCIPE'_text,'t','355');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('356','GIBUTI'_text,'t','356');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('357','NAMIBIA'_text,'t','357');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('358','GUINEA EQUATORIALE'_text,'t','358');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('359','GABON'_text,'t','359');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('401','CANADA'_text,'t','401');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('402','STATI UNITI D''AMERICA'_text,'t','402');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('403','REPUBBLICA DELLA GUAYANA'_text,'t','403');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('404','SURINAME'_text,'t','404');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('405','BARBADOS'_text,'t','405');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('410','COSTA RICA'_text,'t','410');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('411','CUBA'_text,'t','411');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('412','EL SALVADOR'_text,'t','412');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('413','GIAMAICA'_text,'t','413');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('414','GUATEMALA'_text,'t','414');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('415','HAITI'_text,'t','415');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('416','HONDURAS'_text,'t','416');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('417','MESSICO'_text,'t','417');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('418','NICARAGUA'_text,'t','418');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('419','PANAMA'_text,'t','419');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('420','REPUBBLICA DOMINICANA'_text,'t','420');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('428','BELIZE'_text,'t','428');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('440','ARGENTINA'_text,'t','440');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('443','CILE'_text,'t','443');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('444','COLOMBIA'_text,'t','444');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('445','ECUADOR'_text,'t','445');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('446','PARAGUAY'_text,'t','446');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('447','PERU'_text,'t','447');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('449','URUGUAY'_text,'t','449');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('450','VENEZUELA'_text,'t','450');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('460','ANTIGUA E BARBUDA'_text,'t','460');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('461','BAHAMA'_text,'t','461');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('462','DOMINICA'_text,'t','462');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('463','GRENADA'_text,'t','463');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('464','SAINT VINCENT E GRENADINE'_text,'t','464');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('465','SAINT KITTS E NEVIS'_text,'t','465');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('466','SAINT LUCIA'_text,'t','466');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('498','TRINIDAD E TOBAGO'_text,'t','498');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('500','PALESTINA (TERRITORI DELL''AUTONOMIA PALESTINESE)'_text,'t','500');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('501','ARABIA SAUDITA'_text,'t','501');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('502','CIPRO'_text,'t','502');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('503','GIORDANIA'_text,'t','503');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('504','IRAN'_text,'t','504');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('505','IRAQ'_text,'t','505');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('506','ISRAELE'_text,'t','506');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('507','LIBANO'_text,'t','507');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('508','SIRIA'_text,'t','508');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('509','YEMEN'_text,'t','509');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('510','AFGHANISTAN'_text,'t','510');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('519','CAMBOGIA'_text,'t','519');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('520','BANGLADESH'_text,'t','520');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('521','BHUTAN'_text,'t','521');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('522','MYANMAR (EX BIRMANIA)'_text,'t','522');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('523','LAOS'_text,'t','523');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('524','CINA REPUBBLICA POPOLARE'_text,'t','524');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('525','COREA, REPUBBLICA POPOLARE DEMOCRATICA (COREA DEL NORD)'_text,'t','525');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('526','COREA, REPUBBLICA (COREA DEL SUD)'_text,'t','526');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('527','FILIPPINE'_text,'t','527');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('528','GIAPPONE GIAPPONE'_text,'t','528');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('531','BRUNEI'_text,'t','531');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('532','INDONESIA'_text,'t','532');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('533','NEPAL'_text,'t','533');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('534','PAKISTAN'_text,'t','534');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('535','MALDIVE'_text,'t','535');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('536','THAILANDIA'_text,'t','536');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('537','TAIWAN (EX FORMOSA)'_text,'t','537');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('538','VIETNAM'_text,'t','538');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('551','KUWAIT'_text,'t','551');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('552','MONGOLIA REP. POPOLARE'_text,'t','552');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('553','SINGAPORE'_text,'t','553');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('560','BAHEREIN'_text,'t','560');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('561','EMIRATI ARABI UNITI'_text,'t','561');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('562','OMAN'_text,'t','562');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('563','QATAR'_text,'t','563');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('600','MARSHALL, ISOLE'_text,'t','600');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('601','AUSTRALIA'_text,'t','601');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('602','NUOVA ZELANDA'_text,'t','602');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('603','FIGI O VITI'_text,'t','603');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('604','KIRIBATI'_text,'t','604');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('605','PAPUA NUOVA GUINEA'_text,'t','605');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('606','SALOMONE, ISOLE'_text,'t','606');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('607','SAMOA'_text,'t','607');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('608','TONGA'_text,'t','608');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('609','TUVALU'_text,'t','609');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('610','MICRONESIA'_text,'t','610');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('611','NAURU'_text,'t','611');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('612','PALAU'_text,'t','612');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('613','VANUATU'_text,'t','613');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('700','APOLIDI'_text,'t','700');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('701','MONTENEGRO ONTENEGRO'_text,'t','701');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('702','SERBIA,REPUBBLICA DI'_text,'t','702');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('709','KOSOVO'_text,'t','709');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('731','MALAYSIA'_text,'t','731');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('227','IUGOSLAVIA (fino al 04/02/2003)'_text,'f','227');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('231','GROENLANDIA'_text,'f','231');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('238','URSS (fino al 31/03/1992)'_text,'f','238');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('241','SERBIA E MONTENEGRO (fino al 02/06/2006)'_text,'f','241');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('468','ISOLE VERGINI USA'_text,'f','468');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('470','ISOLE VERGINI B. E MONTSERRAT'_text,'f','470');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('471','ISOLE CAYMAN'_text,'f','471');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('472','ISOLE TURKS E CAICOS'_text,'f','472');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('474','PUERTO RICO'_text,'f','474');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('477','BERMUDE'_text,'f','477');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('515','MALESIA (fino al 01/10/1966)'_text,'f','515');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('516','HONG KONG (fino al01/07/1997)'_text,'f','516');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('518','MACAO'_text,'f','518');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('704','TIMOR ORIENTALE (fino al 31/12/1978)'_text,'f','704');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('705','CECOSLOVACCHIA (fino al 01/01/1993)'_text,'f','705');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('706','DIPENDENZE SOVIETICHE'_text,'f','706');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('707','GERMANIA REPUBBLICA DEMOCRATICA (fino al 03/10/1990)'_text,'f','707');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('708','GUAYANA FRANCESE'_text,'f','708');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('711','TERRITORIO DI GAZA'_text,'f','711');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('712','FAER OER (ISOLE)'_text,'f','712');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('713','GIBILTERRA'_text,'f','713');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('714','MAN (ISOLA)'_text,'f','714');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('715','NORMANNE (ISOLE)=ISOLE DEL CANALE'_text,'f','715');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('716','GEORGIA (fino al 01.01.1994)'_text,'f','716');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('717','ARMENIA (fino al 01.01.1994)'_text,'f','717');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('718','AZERBAIGIAN (fino al 01.01.1994)'_text,'f','718');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('719','KIRGHIZISTAN (fino al 01.01.1994)'_text,'f','719');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('720','UZBEKISTAN (fino al 01.01.1994)'_text,'f','720');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('721','TAGIKISTAN (fino al 01.01.1994)'_text,'f','721');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('722','TURKEMENISTAN (fino al 01.01.1994)'_text,'f','722');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('723','KAZAKISTAN (fino al 01.01.1994)'_text,'f','723');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('724','ARABIA MERIDIONALE FEDERAZIONE (fino al 31/12/1975)'_text,'f','724');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('725','ARABIA MERIDIONALE PROTETTORATO (fino al 31/12/1975)'_text,'f','725');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('726','COCOS (ISOLE)'_text,'f','726');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('727','RYUKYU ISOLE (fino al 31/12/1975)'_text,'f','727');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('728','SIKKIM (fino al 31/12/1975)'_text,'f','728');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('729','VIETNAM DEL SUD (fino al 31/12/1977)'_text,'f','729');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('730','VIETNAM DEL NORD (fino al 31/12/1977)'_text,'f','730');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('732','YEMEN REPUBBLICA DEMOCRATICA POPOLARE (fino al 22/05/1990)'_text,'f','732');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('733','BASUTOLAND-SUD AFRICA BRITANNICO (fino al 01/10/1966)'_text,'f','733');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('734','BECIUANIA-SUD AFRICA BRITANNICO (fino al 01/10/1966)'_text,'f','734');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('735','IFNI (fino al 31/12/1984)'_text,'f','735');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('736','LA REUNION (ISOLA)'_text,'f','736');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('737','SAHARA SPAGNOLO (fino al 31/12/1977)'_text,'f','737');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('738','SANT''ELENA (ISOLA)'_text,'f','738');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('739','TERR. FRANCESE DEGLI AFAR E DEGLI ISSA (fino al 31/12/1977)'_text,'f','739');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('740','TANGANICA (fino al 01/10/1966)'_text,'f','740');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('741','ZANZIBAR (fino al 01/10/1966)'_text,'f','741');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('742','MAYOTTE (ISOLA)'_text,'f','742');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('743','SAHARA MERIDIONALE (fino al 31/12/1984)'_text,'f','743');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('744','SAHARA SETTENTRIONALE (fino al 31/12/1984)'_text,'f','744');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('745','BOPHUTHATSWANA (fino al 01/01/1994)'_text,'f','745');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('746','TRANSKEI (fino al 01/01/1994)'_text,'f','746');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('747','VENDA (fino al 01/01/1994)'_text,'f','747');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('748','CISKEI (fino al 01/01/1994)'_text,'f','748');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('749','NYASALAND (fino al 05/07/1964)'_text,'f','749');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('750','CONGO BELGA (fino al 01/01/1960)'_text,'f','750');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('751','SAINT PIERRE ET MIQUELON (ISOLE)'_text,'f','751');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('752','ANTILLE BRITANNICHE (fino al 31.12.1975)'_text,'f','752');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('753','ANTILLE OLANDESI'_text,'f','753');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('754','GUADALUPA'_text,'f','754');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('755','MARTINICA'_text,'f','755');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('756','ANTILLE BRITANNICHE (fino 31/12/1984)'_text,'f','756');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('757','ANGUILLA (ISOLA)'_text,'f','757');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('758','MONTSERRAT'_text,'f','758');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('759','MALVINE=FALKLAND (ISOLE)'_text,'f','759');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('760','CAROLINE (ISOLE)=STATI FEDERATI DI MICRONESIA (22/12/1990)'_text,'f','760');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('761','CHRISTMAS (ISOLA)'_text,'f','761');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('762','COOK (ISOLE)'_text,'f','762');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('763','GILBERT E ELLICE ISOLE (fino al 3/12/1980)'_text,'f','763');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('764','GUAM (ISOLA)'_text,'f','764');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('765','IRIAN OCCIDENTALE'_text,'f','765');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('766','MACQUARIE (ISOLE)'_text,'f','766');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('767','MARCUS ISOLE (fino al 31.12.1975)'_text,'f','767');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('768','MARIANNE (ISOLE)'_text,'f','768');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('769','MIDWAY (ISOLE)'_text,'f','769');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('770','NIUE=SAVAGE (ISOLE)'_text,'f','770');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('771','NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)'_text,'f','771');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('772','NUOVA CALEDONIA (ISOLE E DIPENDENZE)'_text,'f','772');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('773','NUOVE EBRIDI CONDOMINIO FRANCO-INGLESE (fino al 31.12.1980)'_text,'f','773');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('774','NUOVA GUINEA (fino al 31.12.1975)'_text,'f','774');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('775','PAPUASIA (fino al 31.12.1975)'_text,'f','775');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('776','ISOLE CILENE (PASQUA E SALA Y GOMEZ)'_text,'f','776');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('777','PITCAIRN (E DIPENDENZE)'_text,'f','777');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('778','POLINESIA FRANCESE (ISOLE)'_text,'f','778');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('779','SAMOA AMERICANE (ISOLE)'_text,'f','779');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('780','TOKELAU=ISOLE DELL''UNIONE'_text,'f','780');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('781','WALLIS E FUTUNA (ISOLE)'_text,'f','781');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('782','DIPENDENZE CANADESI'_text,'f','782');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('783','DIPENDENZE NORVEGESI ARTICHE'_text,'f','783');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('784','DIPENDENZE AUSTRALIANE'_text,'f','784');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('785','DIPENDENZE BRITANNICHE'_text,'f','785');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('786','DIPENDENZE FRANCESI'_text,'f','786');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('787','DIPENDENZE NEOZELANDESI'_text,'f','787');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('788','DIPENDENZE NORVEGESI ANTARTICHE'_text,'f','788');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('789','DIPENDENZE STATUNITENSI'_text,'f','789');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('790','DIPENDENZE SUDAFRICANE DIPENDENZE SUDAFRICANE'_text,'f','790');
INSERT INTO public.countries(country,description,existing,processing_code) VALUES ('200','ITALIA'_text,'f','200');
