-- Function: unit_tests_translate.procedures(boolean)

-- DROP FUNCTION unit_tests_translate.procedures(boolean);

CREATE OR REPLACE FUNCTION unit_tests_translate.procedures(
    IN _build_dependencies boolean DEFAULT false,
    OUT _results unit_testing.unit_test_result[])
  RETURNS unit_testing.unit_test_result[] AS
$BODY$
<<me>>
DECLARE 
  context               text;
  full_function_name 	text;
  test_name		text = '';
  error			diagnostic.error;
BEGIN
  GET DIAGNOSTICS context = PG_CONTEXT;
  full_function_name = diagnostic.full_function_name(context);
  -- check to build dependencies
  IF _build_dependencies THEN
      PERFORM unit_testing.build_function_dependencies(diagnostic.function_name(context));
    RETURN;
  END IF;  
  -----------------------------
  test_name = 'INSERT procedures';
  -----------------------------
  BEGIN
    INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('24000000000','wikimedia_5_persons_popolate_files','297479000000000','wikimedia_5_popolazione_persone_files','{message}','{messagio}','Sposta le foto dal database delle persone sul file system','{text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('27000000000','wikimedia_2_wikimedia_files_hydration','297479000000000','wikimedia_2_idratazione_files_wikimedia','{_count,_message}','{_conteggio,_messaggio}','Scarica e salva le foto di wikimedia sul database','{integer,text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('33000000000','italian_fiscal_code','297479000000000','codice_fiscale_italiano','{_name,_surname,_sex,_birthday,_country_of_birth,_city_of_birth}','{_nome,_cognome,_sesso,_data_di_nascita,_paese_di_nascita,_citta_di_nascita}','Genera il codice fiscale italiano','{"character varying","character varying",sex,date,smallint,"character varying"}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('12000000000','mime_type','297479000000000','tipo_mime','{p_file_extension}','{p_file_extension}','Richiama a mime_type da file_extension','{file_extension}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('36000000000','file_extension','297479000000000','estensione_file','{p_mime_type}','{p_mime_type}','Richiama a file_extension da mime_type','{mime_type}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('15000000000','wikimedia_0_reset','297479000000000','wikimedia_0_resetta','{_message}','{_messagio}','Rimuove tutte le foto di wikimedia','{text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('18000000000','wikimedia_3_wikimedia_files_popolate_files','297479000000000','wikimedia_3_popolazione_files_wikimedia','{message}','{messagio}','Sposta le foto dal database al file system','{text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('21000000000','wikimedia_4_persons_hydration','297479000000000','wikimedia_4_idratazione_persone','{message}','{messagio}','Scarica e salva le foto di wikimedia sulle persone','{text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300743000000000','topics_upd_rid','297479000000000','argomenti_upd_rid','{p_rv,p_topic,p_description}','{p_rv,p_argomento,p_descrizione}','Aggiorna un argomentazione','{bigint,bigint,"character varying"}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300755000000000','subjects_sel','297479000000000','materie_sel','{p_rv,p_subject,p_school,p_description}','{p_rv,p_materia,p_scuola,p_descrizione}','Seleziona una materia','{bigint,bigint,bigint,"character varying"}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300796000000000','valutations_upd','297479000000000','valutazioni_upd','{p_rv,p_valutation,p_evaluation,p_private,p_note}','{p_rv,p_valutazione,p_nota_di_valutazione,p_privato,p_nota}','Aggiorna una valutazione','{bigint,bigint,"character varying",boolean,boolean}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('711944000000000','where_sequence','297479000000000','dove_sequenza','{name,search_value,table_catalog,table_schema,table_name,column_name,num_time_found}','{nome,valore_da_cercare,tabella_del_catalogo,tabella_dello_schema,nome_della_tabella,nome_della_colonna,num_volte_trovata}','Ritorna dove si trova una sequenza','{text,bigint,information_schema.sql_identifier,information_schema.sql_identifier,information_schema.sql_identifier,information_schema.sql_identifier,bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('42000000000','wikimedia_1_recreate_wikimedia_files_persons','297479000000000','wikimedia_1_ricrea_files_persone_wikimedia','{message}','{messagio}','Scarica e assegna di nuovo a rotazione tutte le foto alle persone da wikimedia','{text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('45000000000','in_any_roles','297479000000000','in_qualsiasi_ruolo','{_roles}','{_ruoli}','Controlla se l''utente corrente è nei ruoli richiesti','{role[]}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('48000000000','in_any_roles','297479000000000','in_qualsiasi_ruolo','{_person,_roles}','{_persona,_ruoli}','Controlla se la persona scritta è nei ruoli richiesti','{bigint,role[]}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('51000000000','in_any_roles','297479000000000','in_qualsiasi_ruolo','{_usename,_roles}','{_utente,_ruoli}','Controlla se l''utente scritto è nei ruoli richiesti','{"character varying",role[]}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300698000000000','valutations_sel','297479000000000','valutazioni_sel','{p_rv,p_valutation,p_evaluation,p_private,p_note}','{p_rv,p_valutazione,p_note_di_valutazione,p_privato,p_nota}','Seleziona una valutazione','{bigint,bigint,"character varying",boolean,boolean}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300739000000000','schools_del_cascade','297479000000000','istituti_del_cascade','{_school_to_delete,_table_name,_record_deleted}','{_scuola_da_cancellare,_nome_tabella,_righe_cancellate}','Elimina una scuola e altre dipendenze','{bigint,"character varying",bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('711941000000000','schools_lookup','297479000000000','consulta_scuole','{_school,_schools}','{_scuola,_scuole}','Ottiene la lista delle consulte per scuola','{bigint,schools}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300691000000000','photo_default','297479000000000','foto_default',NULL,NULL,'Ritorna la foto di default','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('711902000000000','qualifications_tree','297479000000000','albero_qualifiche',NULL,NULL,'Ritorna l''albero delle qualifiche','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('711909000000000','schools_lookup','297479000000000','consulta_scuole','{_school,_schools}','{_scuola,_scuole}','Ottiene la lista delle consulte per scuola','{integer,schools}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('711910000000000','statistics','297479000000000','statistiche','{_message}','{_messaggio}','Ritorna tutte le statistiche','{text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300704000000000','session_person','297479000000000','sessione_persona','{p_school}','{p_scuola}','Controlla la sessione della persona','{bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300765000000000','thumbnail_default','297479000000000','foto_miniatura_demancanza',NULL,NULL,'Ritorna la miniatura di default','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300752000000000','topics_del','297479000000000','argomenti_del','{p_rv,p_topic}','{p_rv,p_argomento}','Elimina un argomentazione','{bigint,bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300754000000000','w_classrooms_ex','297479000000000','w_classi_ex',NULL,NULL,'Ritorna le classi con altre informazioni','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300769000000000','valutations_ins_note','297479000000000','valutazioni_ins_nota','{p_rv,p_note,p_valutation}','{p_rv,p_nota,p_valutazione}','Inserisce una nota per la valutazione','{bigint,bigint,bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('173000000000','classrooms_lookup','297479000000000',NULL,'{_classroom,_classrooms}',NULL,NULL,'{bigint,classrooms}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300717000000000','weekly_timetable_xt_teacher','297479000000000','orario_settimanale_xt_docente','{p_weekly_timetable,period,lunedì,martedì,mercoledì,giovedì,venerdì,sabato}','{p_orario_settimanale,periodo,lunedì,martedì,mercoledì,giovedì,venerdì,sabato}','Visualizza l''orario settimanale dov''è presente il professore richiesto','{bigint,text,text,text,text,text,text,text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300795000000000','valutations_del','297479000000000','valutazioni_del','{p_rv,p_valutation}','{p_rv,p_valutazione}','Elimina una valutazione','{bigint,bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300714000000000','w_weekly_timetables_days_ex','297479000000000','w_orari_settimanali_giorni_ex',NULL,NULL,'Ritorna l''orario settimanale con tutti i giorni e altre informazioni','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300787000000000','w_classrooms_students_ex','297479000000000','w_classi_alunni_ex',NULL,NULL,'Ritorna gli studenti di tutte le classi con altre informazioni','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300789000000000','w_weekly_timetable_ex','297479000000000','w_orario_settimanale_ex',NULL,NULL,'Ritorna l''orario settimanale con altre informazioni','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300702000000000','persons_sel_thumbnail','297479000000000','persone_sel_foto_miniatura','{p_person}','{p_persona}','Seleziona la miniatura di una persona','{bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300719000000000','persons_surname_name','297479000000000','personae_cognome_nome','{p_person}','{p_persona}','Ritorna il nome e cognome di una persona','{bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300720000000000','weekly_timetable_xt_subject','297479000000000','orario_settimanale_xt_materia','{p_weekly_timetable,period,lunedì,martedì,mercoledì,giovedì,venerdì,sabato}','{p_orario_settimanale,periodo,lunedì,martedì,mercoledì,giovedì,venerdì,sabato}','Visualizza l''orario settimanale dov''è presente la materia richiesta','{bigint,text,text,text,text,text,text,text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300725000000000','subjects_del','297479000000000','materie_del','{p_rv,p_subject}','{p_rv,p_materia}','Elimina una materia','{bigint,bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300746000000000','valutations_upd_grade','297479000000000','valutazioni_upd_voto','{p_rv,p_valutation,p_grade}','{p_rv,p_valutazione,p_voto}','Aggiorna il sistema di valutazione','{bigint,bigint,bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300750000000000','topics_ins_rid','297479000000000','argomenti_ins_rid','{p_rv,p_topic,p_subject,p_description,p_classroom}','{p_rv,p_argomento,p_materia,p_descrizione,p_classe}','Inserisce un argomentazione','{bigint,bigint,bigint,"character varying",bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300758000000000','schools_del','297479000000000','istituti_del','{p_rv,p_school}','{p_rv,p_scuola}','Elimina una scuola','{bigint,bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300779000000000','grid_valutations_rows_by_classroom_teacher_subject','297479000000000','griglia_valutazioni_righe_by_classe_docente_materia','{p_classroom,p_teacher,p_subject,student,surname,name,absences,delays,leavings,out_of_classroom,notes,faults,behavior,rvs,valutations,grades}','{p_classe,p_insegnante,p_materia,studente,cognome,nome,assenze,ritardi,uscite,fuori_classe,note,mancanze,condotta,rvs,valutazioni,voti}','Visualizza la griglia delle valutazioni ordinata per righe','{bigint,bigint,bigint,bigint,"character varying","character varying",integer,integer,integer,integer,integer,integer,"character varying",bigint[],bigint[],bigint[]}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('300800000000000','w_classrooms_teachers_subjects_ex','297479000000000','w_classi_docenti_materie_ex',NULL,NULL,'Ritorna tutti gli insegnanti con la loro materia e altre informazioni','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('306028000000000','schools_enabled','297479000000000','scuole_attive',NULL,NULL,'Ritorna le scuole attive','{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('158000000000','subjects_ins','297479000000000',NULL,'{_rv,_subject,_school,_description}',NULL,NULL,'{bigint,bigint,bigint,"character varying"}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('159000000000','schools_ins','297479000000000',NULL,'{_rv,_school,_description,_processing_code,_mnemonic,_example}',NULL,'Insert a school','{bigint,bigint,"character varying","character varying","character varying",boolean}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('160000000000','current_persons','297479000000000',NULL,NULL,NULL,NULL,'{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('161000000000','login','297479000000000',NULL,'{_username,_password}',NULL,NULL,'{text,text}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('162000000000','schools_ins','297479000000000',NULL,'{_rv,_school,_description,_processing_code,_mnemonic,_example,_logo}',NULL,NULL,'{bigint,bigint,"character varying","character varying","character varying",boolean,image}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('163000000000','schools_sel_logo','297479000000000',NULL,'{_school,_logo}',NULL,'<public>','{bigint,image}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('164000000000','schools_sel','297479000000000',NULL,'{_rv,_school,_description,_processing_code,_mnemonic,_example,_behavior,_logo_mime_type,_logo_content}',NULL,'Select a school','{bigint,bigint,"character varying","character varying","character varying",boolean,bigint,mime_type_image,bytea}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('165000000000','schools_upd','297479000000000',NULL,'{_rv,_school,_description,_processing_code,_mnemonic,_example,_behavior,_logo}',NULL,NULL,'{bigint,bigint,"character varying","character varying","character varying",boolean,bigint,image}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('166000000000','schools_upd_logo','297479000000000',NULL,'{_rv,_school,_logo}',NULL,'Update the logo of a school','{bigint,bigint,image}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('167000000000','schools_upd','297479000000000',NULL,'{_rv,_school,_description,_processing_code,_mnemonic,_example,_behavior}',NULL,NULL,'{bigint,bigint,"character varying","character varying","character varying",boolean,bigint}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('168000000000','session_persons','297479000000000',NULL,NULL,NULL,NULL,'{}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('169000000000','subjects_upd','297479000000000',NULL,'{_rv,_subject,_school,_description}',NULL,'Update a subject','{bigint,bigint,bigint,"character varying"}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('170000000000','valutations_ins','297479000000000',NULL,'{_rv,_valutation,_classroom_student,_subject,_grade_type,_topic,_grade,_evaluation,_private,_teacher,_on_date}',NULL,NULL,'{bigint,bigint,bigint,bigint,bigint,bigint,bigint,"character varying",boolean,bigint,date}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('172000000000','classrooms_lookup','297479000000000',NULL,'{_classroom,_classrooms}',NULL,NULL,'{integer,classrooms}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('174000000000','persons_lookup','297479000000000',NULL,'{_person,_persons}',NULL,NULL,'{integer,persons}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('175000000000','persons_lookup','297479000000000',NULL,'{_person,_persons}',NULL,NULL,'{bigint,persons}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('176000000000','regions_lookup','297479000000000',NULL,'{_region,_regions}',NULL,NULL,'{integer,regions}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('177000000000','school_years_lookup','297479000000000',NULL,'{_school_year,_school_years}',NULL,NULL,'{integer,school_years}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('178000000000','school_years_lookup','297479000000000',NULL,'{_school_year,_school_years}',NULL,NULL,'{bigint,school_years}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('179000000000','subjects_lookup','297479000000000',NULL,'{_subject,_subjects}',NULL,NULL,'{integer,subjects}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('180000000000','subjects_lookup','297479000000000',NULL,'{_subject,_subjects}',NULL,NULL,'{bigint,subjects}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('181000000000','cities_lookup','297479000000000',NULL,'{_city,_cities}',NULL,NULL,'{character,cities}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('182000000000','districts_lookup','297479000000000',NULL,'{_district,_districts}',NULL,NULL,'{character,districts}');
INSERT INTO translate.procedures(procedure,name,language,translation,arguments_name,arguments_name_translation,comment,arguments_type) VALUES ('183000000000','regions_lookup','297479000000000',NULL,'{_region,_regions}',NULL,NULL,'{smallint,regions}');


    _results =  _results || assert.pass(full_function_name, test_name);

    EXCEPTION
      WHEN OTHERS THEN 
        GET STACKED DIAGNOSTICS error.returned_sqlstate = RETURNED_SQLSTATE, error.message_text = MESSAGE_TEXT, error.schema_name = SCHEMA_NAME, error.table_name = TABLE_NAME, error.column_name = COLUMN_NAME, error.constraint_name = CONSTRAINT_NAME, error.pg_exception_context = PG_EXCEPTION_CONTEXT, error.pg_exception_detail = PG_EXCEPTION_DETAIL, error.pg_exception_hint = PG_EXCEPTION_HINT, error.pg_datatype_name = PG_DATATYPE_NAME;
        _results = _results || assert.fail(full_function_name, test_name, 'INSERT public.procedures FAILED'::text, error);   
        RETURN; 
  END;
  RETURN; 
END
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION unit_tests_translate.procedures(boolean)
  OWNER TO postgres;
